import type { SystemEvent } from "@/types";

/** Legal-domain events — surfaced in the Legal Center and Event Center. */
export const legalEvents: SystemEvent[] = [
  {
    id: "le-01",
    type: "contract.high_risk.detected",
    source: "Contract Review Agent",
    message: "High risk detected in Cloud Infra Renewal (Northwind) — liability cap missing",
    severity: "error",
    timestamp: "just now",
  },
  {
    id: "le-02",
    type: "contract.review.completed",
    source: "Contract Review Agent",
    message: "Legal review completed for Vendor Services Agreement (Umbrella Co)",
    severity: "success",
    timestamp: "6m ago",
  },
  {
    id: "le-03",
    type: "compliance.violation",
    source: "Compliance Agent",
    message: "Unapproved subprocessor detected — critical violation VIO-14",
    severity: "error",
    timestamp: "1h ago",
  },
  {
    id: "le-04",
    type: "risk.escalated",
    source: "Risk Assessment Agent",
    message: "Vendor risk RSK-33 escalated to Director — subprocessor exposure",
    severity: "warning",
    timestamp: "2h ago",
  },
  {
    id: "le-05",
    type: "policy.pending_approval",
    source: "Policy Management Agent",
    message: "AI Governance Policy v1.0 drafted — awaiting Director approval",
    severity: "info",
    timestamp: "2h ago",
  },
  {
    id: "le-06",
    type: "regulation.high_impact",
    source: "Regulatory Monitoring Agent",
    message: "EU AI Act high-risk classification — policy update required",
    severity: "warning",
    timestamp: "3h ago",
  },
  {
    id: "le-07",
    type: "contract.generated",
    source: "Contract Generation Agent",
    message: "Reseller Partnership draft generated for Contoso Ltd",
    severity: "info",
    timestamp: "4h ago",
  },
  {
    id: "le-08",
    type: "contract.clause.missing",
    source: "Contract Review Agent",
    message: "IP Ownership clause missing in 43% of active contracts",
    severity: "warning",
    timestamp: "5h ago",
  },
  {
    id: "le-09",
    type: "ip.domain.expiring",
    source: "IP & Trademark Agent",
    message: "hebun.com expires in 21 days — renewal recommended",
    severity: "warning",
    timestamp: "6h ago",
  },
  {
    id: "le-10",
    type: "compliance.restored",
    source: "Compliance Agent",
    message: "Retention policy overrun remediated — compliance restored",
    severity: "success",
    timestamp: "yesterday",
  },
];
