import type { SystemEvent } from "@/types";

/** HR-domain events — surfaced in the HR Center and Event Center. */
export const hrEvents: SystemEvent[] = [
  {
    id: "hre-01",
    type: "candidate.applied",
    source: "Recruiting Agent",
    message: "New application for Senior AI Engineer — 24 candidates in pipeline",
    severity: "info",
    timestamp: "just now",
  },
  {
    id: "hre-02",
    type: "candidate.screened",
    source: "Candidate Screening Agent",
    message: "Elif Yılmaz screened — 92% technical match, moved to interview",
    severity: "success",
    timestamp: "4m ago",
  },
  {
    id: "hre-03",
    type: "interview.scheduled",
    source: "Interview Scheduling Agent",
    message: "Interview booked — Elif Yılmaz today at 14:00",
    severity: "info",
    timestamp: "9m ago",
  },
  {
    id: "hre-04",
    type: "interview.feedback.pending",
    source: "Interview Scheduling Agent",
    message: "Feedback pending for John Carter (Data Analyst)",
    severity: "warning",
    timestamp: "1h ago",
  },
  {
    id: "hre-05",
    type: "onboarding.started",
    source: "Onboarding Agent",
    message: "David Kim onboarding started — access requests pending",
    severity: "info",
    timestamp: "2h ago",
  },
  {
    id: "hre-06",
    type: "performance.review.due",
    source: "Performance Review Agent",
    message: "12 Q2 reviews due — Sara Ahmadi and David Kim flagged",
    severity: "warning",
    timestamp: "3h ago",
  },
  {
    id: "hre-07",
    type: "learning.completed",
    source: "Learning & Development Agent",
    message: "Nora Haddad completed Financial Modeling — certified",
    severity: "success",
    timestamp: "5h ago",
  },
  {
    id: "hre-08",
    type: "employee.request",
    source: "Employee Support Agent",
    message: "New payroll question from Sara Ahmadi — ticket HRT-71 opened",
    severity: "info",
    timestamp: "12m ago",
  },
  {
    id: "hre-09",
    type: "retention.risk",
    source: "HR Agent",
    message: "Retention risk flagged for 3 employees — low engagement signals",
    severity: "error",
    timestamp: "6h ago",
  },
  {
    id: "hre-10",
    type: "offboarding.started",
    source: "Offboarding Agent",
    message: "Offboarding started for Omar Farouk — last day Jul 20",
    severity: "info",
    timestamp: "yesterday",
  },
];
