import assert from "node:assert/strict";
import { bindAuthorityIdentityChain, createAuthorityIdentityChain, createRuntimeAuthorityRequest, RUNTIME_AUTHORITY_PRINCIPAL_TYPES, validateAuthorityIdentityChain } from "../../src/features/director-command";

const request = createRuntimeAuthorityRequest({ requestId: "authority-4d2", subject: { subjectId: "director-1", subjectType: "director", tenantScope: "tenant-a", executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "agent", tenantScope: "tenant-a", executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executable: false, authoritative: false }, context: { correlationId: "correlation-4d2", timestamp: "2026-07-23T12:00:00.000Z", metadata: {}, executable: false, authoritative: false }, executable: false, authoritative: false });
const identity = { executionId: "execution-4d2", correlationId: "correlation-4d2", commandId: "agent.restart" as const, commandVersion: "1.0.0", targetIdentity: "agent-1", adapterFamily: "agent" as const, capability: "agent.lifecycle" as const, creationTimestamp: "2026-07-23T12:00:00.000Z", architectureVersion: "1.0.0" as const, executable: false as const, authoritative: false as const };
const input = { tenant: { tenantId: "tenant-a", tenantType: "organization" as const, metadata: { labels: ["primary"] }, executable: false as const, authoritative: false as const }, workspace: { workspaceId: "workspace-a", workspaceType: "workspace" as const, tenantId: "tenant-a", metadata: {}, executable: false as const, authoritative: false as const }, principal: { principalId: "principal-a", principalType: "human" as const, tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false as const, authoritative: false as const }, subject: { subjectId: "subject-a", subjectType: "authority_subject" as const, principalId: "principal-a", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false as const, authoritative: false as const }, delegations: [{ delegationId: "delegation-a", tenantId: "tenant-a", workspaceId: "workspace-a", delegatedByType: "human" as const, delegatedById: "principal-a", agentId: "agent-1", metadata: {}, executable: false as const, authoritative: false as const }], agent: { agentId: "agent-1", agentType: "agent" as const, tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false as const, authoritative: false as const }, execution: { executionIdentity: identity, authorityRequestId: "authority-4d2", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false as const, authoritative: false as const }, authorityRequest: request, executable: false as const, authoritative: false as const };
const chain = createAuthorityIdentityChain(input);
assert.equal(Object.isFrozen(chain), true); assert.equal(Object.isFrozen(chain.delegations), true); assert.equal(validateAuthorityIdentityChain(chain).status, "bound"); assert.equal(bindAuthorityIdentityChain(chain).authoritative, false); assert.notEqual(chain.tenant.metadata, input.tenant.metadata); assert.deepEqual(RUNTIME_AUTHORITY_PRINCIPAL_TYPES, ["human", "service", "workflow", "agent_delegate"]);
assert.equal(validateAuthorityIdentityChain(createAuthorityIdentityChain({ ...input, tenant: { ...input.tenant, tenantId: "tenant-b" } })).error?.code, "TENANT_MISMATCH");
assert.equal(validateAuthorityIdentityChain(createAuthorityIdentityChain({ ...input, workspace: { ...input.workspace, workspaceId: "workspace-b" } })).error?.code, "WORKSPACE_MISMATCH");
assert.equal(validateAuthorityIdentityChain(createAuthorityIdentityChain({ ...input, execution: { ...input.execution, executionIdentity: { ...identity, targetIdentity: "other" } } })).error?.code, "EXECUTION_IDENTITY_MISMATCH");
assert.throws(() => createAuthorityIdentityChain({ ...input, delegations: [] }));
assert.throws(() => createAuthorityIdentityChain({ ...input, principal: { ...input.principal, principalType: "unknown" } } as never));
assert.throws(() => createAuthorityIdentityChain({ ...input, tenant: { ...input.tenant, metadata: { callback: () => undefined } } } as never));
assert.throws(() => createAuthorityIdentityChain({ ...input, tenant: { ...input.tenant, metadata: { promise: Promise.resolve() } } } as never));
assert.throws(() => createAuthorityIdentityChain({ ...input, tenant: { ...input.tenant, metadata: { marker: Symbol("x") } } } as never));
assert.throws(() => { (chain.tenant.metadata.labels as unknown as string[]).push("mutation"); });
console.log("runtime authority identity checks passed");
