import assert from "node:assert/strict";
import { createAuthorityIdentityChain, createRuntimeAuthorityRequest, createRuntimePolicy, RUNTIME_POLICY_EFFECTS, validateRuntimePolicy, validateRuntimePolicyResult } from "../../src/features/director-command";

const request = createRuntimeAuthorityRequest({ requestId: "authority-4d3", subject: { subjectId: "director-1", subjectType: "director", tenantScope: "tenant-a", executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "agent", tenantScope: "tenant-a", executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executable: false, authoritative: false }, context: { correlationId: "correlation-4d3", timestamp: "2026-07-23T12:00:00.000Z", metadata: {}, executable: false, authoritative: false }, executable: false, authoritative: false });
const execution = { executionId: "execution-4d3", correlationId: "correlation-4d3", commandId: "agent.restart" as const, commandVersion: "1.0.0", targetIdentity: "agent-1", adapterFamily: "agent" as const, capability: "agent.lifecycle" as const, creationTimestamp: "2026-07-23T12:00:00.000Z", architectureVersion: "1.0.0" as const, executable: false as const, authoritative: false as const };
const identity = createAuthorityIdentityChain({ tenant: { tenantId: "tenant-a", tenantType: "organization", metadata: {}, executable: false, authoritative: false }, workspace: { workspaceId: "workspace-a", workspaceType: "workspace", tenantId: "tenant-a", metadata: {}, executable: false, authoritative: false }, principal: { principalId: "principal-a", principalType: "human", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, subject: { subjectId: "subject-a", subjectType: "authority_subject", principalId: "principal-a", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, delegations: [{ delegationId: "delegation-a", tenantId: "tenant-a", workspaceId: "workspace-a", delegatedByType: "human", delegatedById: "principal-a", agentId: "agent-1", metadata: {}, executable: false, authoritative: false }], agent: { agentId: "agent-1", agentType: "agent", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, execution: { executionIdentity: execution, authorityRequestId: "authority-4d3", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, authorityRequest: request, executable: false, authoritative: false });
const input = { metadata: { policyId: "policy-4d3", version: { value: "1.0.0", executable: false as const, authoritative: false as const }, metadata: { tags: ["declarative"] }, executable: false as const, authoritative: false as const }, subject: { identity, metadata: {}, executable: false as const, authoritative: false as const }, action: { actionId: "agent.restart", actionType: "lifecycle", executionId: "execution-4d3", metadata: {}, executable: false as const, authoritative: false as const }, resource: { resourceId: "agent-1", resourceType: "runtime_target" as const, targetIdentity: "agent-1", metadata: {}, executable: false as const, authoritative: false as const }, environment: { environment: "production" as const, metadata: { tenant_region: "EU" }, executable: false as const, authoritative: false as const }, conditions: [{ conditionId: "condition-a", expression: "tenant == EU", metadata: {}, executable: false as const, authoritative: false as const }], effect: "allow" as const, obligations: [{ obligationId: "obligation-a", obligationType: "audit_required" as const, metadata: {}, executable: false as const, authoritative: false as const }], executable: false as const, authoritative: false as const };
const policy = createRuntimePolicy(input);
assert.equal(Object.isFrozen(policy), true); assert.equal(Object.isFrozen(policy.conditions), true); assert.equal(validateRuntimePolicy(policy).status, "valid"); assert.equal(validateRuntimePolicyResult(policy).authoritative, false); assert.notEqual(policy.metadata.metadata, input.metadata.metadata); assert.deepEqual(RUNTIME_POLICY_EFFECTS, ["allow", "deny", "approval_required", "not_applicable"]);
assert.equal(validateRuntimePolicy(createRuntimePolicy({ ...input, action: { ...input.action, executionId: "other" } })).error?.code, "INVALID_POLICY_ACTION");
assert.equal(validateRuntimePolicy(createRuntimePolicy({ ...input, resource: { ...input.resource, targetIdentity: "other" } })).error?.code, "INVALID_POLICY_RESOURCE");
assert.throws(() => createRuntimePolicy({ ...input, conditions: [{ ...input.conditions[0]!, metadata: { callback: () => undefined } }] } as never));
assert.throws(() => createRuntimePolicy({ ...input, environment: { ...input.environment, metadata: { promise: Promise.resolve() } } } as never));
assert.throws(() => createRuntimePolicy({ ...input, metadata: { ...input.metadata, metadata: { marker: Symbol("x") } } } as never));
assert.throws(() => { (policy.metadata.metadata.tags as unknown as string[]).push("mutation"); });
console.log("runtime policy checks passed");
