import assert from "node:assert/strict";
import { createAuthorityIdentityChain, createRuntimeAuthorityRequest, createRuntimeExecutionPermit, createRuntimeHumanApproval, createRuntimePolicy, createRuntimeRiskClassification, RUNTIME_PERMIT_STATUSES, validateRuntimeExecutionPermit, validateRuntimeExecutionPermitResult } from "../../src/features/director-command";

const request = createRuntimeAuthorityRequest({ requestId: "authority-4d6", subject: { subjectId: "director-1", subjectType: "director", tenantScope: "tenant-a", executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "agent", tenantScope: "tenant-a", executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executable: false, authoritative: false }, context: { correlationId: "correlation-4d6", timestamp: "2026-07-23T12:00:00.000Z", metadata: {}, executable: false, authoritative: false }, executable: false, authoritative: false });
const execution = { executionId: "execution-4d6", correlationId: "correlation-4d6", commandId: "agent.restart" as const, commandVersion: "1.0.0", targetIdentity: "agent-1", adapterFamily: "agent" as const, capability: "agent.lifecycle" as const, creationTimestamp: "2026-07-23T12:00:00.000Z", architectureVersion: "1.0.0" as const, executable: false as const, authoritative: false as const };
const identity = createAuthorityIdentityChain({ tenant: { tenantId: "tenant-a", tenantType: "organization", metadata: {}, executable: false, authoritative: false }, workspace: { workspaceId: "workspace-a", workspaceType: "workspace", tenantId: "tenant-a", metadata: {}, executable: false, authoritative: false }, principal: { principalId: "principal-a", principalType: "human", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, subject: { subjectId: "subject-a", subjectType: "authority_subject", principalId: "principal-a", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, delegations: [{ delegationId: "delegation-a", tenantId: "tenant-a", workspaceId: "workspace-a", delegatedByType: "human", delegatedById: "principal-a", agentId: "agent-1", metadata: {}, executable: false, authoritative: false }], agent: { agentId: "agent-1", agentType: "agent", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, execution: { executionIdentity: execution, authorityRequestId: "authority-4d6", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, authorityRequest: request, executable: false, authoritative: false });
const policy = createRuntimePolicy({ metadata: { policyId: "policy-4d6", version: { value: "1.0.0", executable: false, authoritative: false }, metadata: {}, executable: false, authoritative: false }, subject: { identity, metadata: {}, executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executionId: "execution-4d6", metadata: {}, executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "runtime_target", targetIdentity: "agent-1", metadata: {}, executable: false, authoritative: false }, environment: { environment: "production", metadata: {}, executable: false, authoritative: false }, conditions: [], effect: "approval_required", obligations: [], executable: false, authoritative: false });
const classification = createRuntimeRiskClassification({ metadata: { riskClassificationId: "risk-4d6", authorityRequestId: "authority-4d6", policyId: "policy-4d6", tenantId: "tenant-a", workspaceId: "workspace-a", executionId: "execution-4d6", actionId: "agent.restart", resourceId: "agent-1", version: { value: "1.0.0", executable: false, authoritative: false }, metadata: {}, executable: false, authoritative: false }, authorityRequest: request, policy, profile: { level: "high", domains: ["security"], impactScope: "workspace", blastRadius: "limited", reversibility: "compensatable", dataSensitivity: "restricted", sideEffects: ["internal_state_change"], factors: [], metadata: {}, executable: false, authoritative: false }, approval: { mode: "single_human", quorum: { requiredCount: 1, distinctApproversRequired: false, roles: [], orderingRequired: false, separationOfDutiesRequired: false, executable: false, authoritative: false }, constraints: [], metadata: {}, executable: false, authoritative: false }, executable: false, authoritative: false });
const approval = createRuntimeHumanApproval({ record: { metadata: { approvalId: "approval-4d6", authorityRequestId: "authority-4d6", riskClassificationId: "risk-4d6", version: { value: "1.0.0", executable: false, authoritative: false }, metadata: {}, executable: false, authoritative: false }, status: "approved", decision: { value: "approve", reason: "Reviewed.", executable: false, authoritative: false }, actor: { actorId: "approver-1", identity, metadata: {}, executable: false, authoritative: false }, evidence: [{ evidenceType: "ticket_reference", reference: "TICKET-1", metadata: {}, executable: false, authoritative: false }], timestamp: { recordedAt: "2026-07-23T12:00:00.000Z", executable: false, authoritative: false }, executable: false, authoritative: false }, classification, executable: false, authoritative: false });
const input = { identity: { permitId: "permit-4d6", correlationId: "correlation-4d6", executionId: "execution-4d6", executable: false as const, authoritative: false as const }, status: "issued" as const, metadata: { authorityRequestId: "authority-4d6", policyId: "policy-4d6", riskClassificationId: "risk-4d6", approvalId: "approval-4d6", schemaVersion: "1.0.0", version: { value: "1.0.0", executable: false as const, authoritative: false as const }, metadata: { labels: ["evidence"] }, executable: false as const, authoritative: false as const }, references: { authorityRequest: request, identity, policy, riskClassification: classification, approvalRequirement: classification.approval, humanApproval: approval, executionIdentity: execution, executable: false as const, authoritative: false as const }, evidence: [{ evidenceType: "policy_version" as const, reference: "1.0.0", metadata: {}, executable: false as const, authoritative: false as const }], executable: false as const, authoritative: false as const };
const permit = createRuntimeExecutionPermit(input);
assert.equal(Object.isFrozen(permit), true); assert.equal(Object.isFrozen(permit.evidence), true); assert.equal(validateRuntimeExecutionPermit(permit).status, "valid"); assert.equal(validateRuntimeExecutionPermitResult(permit).authoritative, false); assert.notEqual(permit.metadata.metadata, input.metadata.metadata); assert.deepEqual(RUNTIME_PERMIT_STATUSES, ["issued", "expired", "revoked"]);
assert.equal(validateRuntimeExecutionPermit(createRuntimeExecutionPermit({ ...input, metadata: { ...input.metadata, authorityRequestId: "other" } })).error?.code, "AUTHORITY_MISMATCH");
assert.equal(validateRuntimeExecutionPermit(createRuntimeExecutionPermit({ ...input, metadata: { ...input.metadata, policyId: "other" } })).error?.code, "POLICY_MISMATCH");
assert.equal(validateRuntimeExecutionPermit(createRuntimeExecutionPermit({ ...input, metadata: { ...input.metadata, riskClassificationId: "other" } })).error?.code, "RISK_MISMATCH");
assert.equal(validateRuntimeExecutionPermit(createRuntimeExecutionPermit({ ...input, metadata: { ...input.metadata, approvalId: "other" } })).error?.code, "APPROVAL_MISMATCH");
assert.equal(validateRuntimeExecutionPermit(createRuntimeExecutionPermit({ ...input, references: { ...input.references, identity: { ...identity, tenant: { ...identity.tenant, tenantId: "tenant-b" } } } } as never)).error?.code, "IDENTITY_MISMATCH");
assert.throws(() => createRuntimeExecutionPermit({ ...input, evidence: [{ ...input.evidence[0]!, metadata: { callback: () => undefined } }] } as never));
assert.throws(() => createRuntimeExecutionPermit({ ...input, metadata: { ...input.metadata, metadata: { promise: Promise.resolve() } } } as never));
assert.throws(() => createRuntimeExecutionPermit({ ...input, metadata: { ...input.metadata, metadata: { symbol: Symbol("x") } } } as never));
const cyclic: { self?: unknown } = {}; cyclic.self = cyclic;
assert.throws(() => createRuntimeExecutionPermit({ ...input, metadata: { ...input.metadata, metadata: cyclic } } as never));
class AdapterLike { readonly name = "adapter"; }
assert.throws(() => createRuntimeExecutionPermit({ ...input, evidence: [{ ...input.evidence[0]!, metadata: { adapter: new AdapterLike() } }] } as never));
assert.throws(() => { (permit.metadata.metadata.labels as unknown as string[]).push("mutation"); });
console.log("runtime execution permit checks passed");
