import assert from "node:assert/strict";
import { createAuthorityIdentityChain, createRuntimeAuthorityRequest, createRuntimePolicy, createRuntimeRiskClassification, RUNTIME_APPROVAL_MODES, RUNTIME_RISK_LEVELS, validateRuntimeRiskClassification, validateRuntimeRiskClassificationResult } from "../../src/features/director-command";

const request = createRuntimeAuthorityRequest({ requestId: "authority-4d4", subject: { subjectId: "director-1", subjectType: "director", tenantScope: "tenant-a", executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "agent", tenantScope: "tenant-a", executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executable: false, authoritative: false }, context: { correlationId: "correlation-4d4", timestamp: "2026-07-23T12:00:00.000Z", metadata: {}, executable: false, authoritative: false }, executable: false, authoritative: false });
const execution = { executionId: "execution-4d4", correlationId: "correlation-4d4", commandId: "agent.restart" as const, commandVersion: "1.0.0", targetIdentity: "agent-1", adapterFamily: "agent" as const, capability: "agent.lifecycle" as const, creationTimestamp: "2026-07-23T12:00:00.000Z", architectureVersion: "1.0.0" as const, executable: false as const, authoritative: false as const };
const identity = createAuthorityIdentityChain({ tenant: { tenantId: "tenant-a", tenantType: "organization", metadata: {}, executable: false, authoritative: false }, workspace: { workspaceId: "workspace-a", workspaceType: "workspace", tenantId: "tenant-a", metadata: {}, executable: false, authoritative: false }, principal: { principalId: "principal-a", principalType: "human", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, subject: { subjectId: "subject-a", subjectType: "authority_subject", principalId: "principal-a", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, delegations: [{ delegationId: "delegation-a", tenantId: "tenant-a", workspaceId: "workspace-a", delegatedByType: "human", delegatedById: "principal-a", agentId: "agent-1", metadata: {}, executable: false, authoritative: false }], agent: { agentId: "agent-1", agentType: "agent", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, execution: { executionIdentity: execution, authorityRequestId: "authority-4d4", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, authorityRequest: request, executable: false, authoritative: false });
const policy = createRuntimePolicy({ metadata: { policyId: "policy-4d4", version: { value: "1.0.0", executable: false, authoritative: false }, metadata: {}, executable: false, authoritative: false }, subject: { identity, metadata: {}, executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executionId: "execution-4d4", metadata: {}, executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "runtime_target", targetIdentity: "agent-1", metadata: {}, executable: false, authoritative: false }, environment: { environment: "production", metadata: {}, executable: false, authoritative: false }, conditions: [], effect: "allow", obligations: [], executable: false, authoritative: false });
const input = { metadata: { riskClassificationId: "risk-4d4", authorityRequestId: "authority-4d4", policyId: "policy-4d4", tenantId: "tenant-a", workspaceId: "workspace-a", executionId: "execution-4d4", actionId: "agent.restart", resourceId: "agent-1", version: { value: "1.0.0", executable: false as const, authoritative: false as const }, metadata: { labels: ["descriptive"] }, executable: false as const, authoritative: false as const }, authorityRequest: request, policy, profile: { level: "high" as const, domains: ["operational", "security"] as const, impactScope: "workspace" as const, blastRadius: "limited" as const, reversibility: "compensatable" as const, dataSensitivity: "restricted" as const, sideEffects: ["internal_state_change"] as const, factors: [{ factorType: "privileged_operation", factorValue: "declared", severityContribution: "elevating" as const, sourceReference: "policy-4d4", metadata: {}, executable: false as const, authoritative: false as const }], metadata: {}, executable: false as const, authoritative: false as const }, approval: { mode: "dual_human" as const, quorum: { requiredCount: 2, distinctApproversRequired: true, roles: [{ role: "security_officer" as const, minimumCount: 1, executable: false as const, authoritative: false as const }], orderingRequired: false, separationOfDutiesRequired: true, executable: false as const, authoritative: false as const }, constraints: ["distinct_approvers", "same_tenant", "separation_of_duties"] as const, metadata: {}, executable: false as const, authoritative: false as const }, executable: false as const, authoritative: false as const };
const classification = createRuntimeRiskClassification(input);
assert.equal(Object.isFrozen(classification), true); assert.equal(Object.isFrozen(classification.profile.factors), true); assert.equal(validateRuntimeRiskClassification(classification).status, "valid"); assert.equal(validateRuntimeRiskClassificationResult(classification).authoritative, false); assert.notEqual(classification.metadata.metadata, input.metadata.metadata); assert.deepEqual(RUNTIME_RISK_LEVELS, ["negligible", "low", "moderate", "high", "critical"]); assert.equal(RUNTIME_APPROVAL_MODES.includes("none"), true);
assert.equal(validateRuntimeRiskClassification(createRuntimeRiskClassification({ ...input, metadata: { ...input.metadata, tenantId: "tenant-b" } })).error?.code, "TENANT_MISMATCH");
assert.equal(validateRuntimeRiskClassification(createRuntimeRiskClassification({ ...input, approval: { ...input.approval, quorum: { ...input.approval.quorum, requiredCount: 1 } } })).error?.code, "CONTRADICTORY_APPROVAL_REQUIREMENT");
assert.equal(validateRuntimeRiskClassification(createRuntimeRiskClassification({ ...input, approval: { ...input.approval, mode: "none", quorum: { ...input.approval.quorum, requiredCount: 0, roles: [] }, constraints: [] } })).status, "valid");
assert.throws(() => createRuntimeRiskClassification({ ...input, profile: { ...input.profile, metadata: { callback: () => undefined } } } as never));
assert.throws(() => createRuntimeRiskClassification({ ...input, approval: { ...input.approval, metadata: { promise: Promise.resolve() } } } as never));
assert.throws(() => createRuntimeRiskClassification({ ...input, metadata: { ...input.metadata, metadata: { marker: Symbol("x") } } } as never));
assert.throws(() => { (classification.metadata.metadata.labels as unknown as string[]).push("mutation"); });
console.log("runtime risk classification checks passed");
