import assert from "node:assert/strict";
import { createAuthorityIdentityChain, createRuntimeAuthorityRequest, createRuntimeHumanApproval, createRuntimePolicy, createRuntimeRiskClassification, RUNTIME_APPROVAL_DECISIONS, RUNTIME_APPROVAL_STATUSES, validateRuntimeHumanApproval, validateRuntimeHumanApprovalResult } from "../../src/features/director-command";

function frozen<T>(value: T): T { if (value && typeof value === "object") { for (const entry of Object.values(value as object)) frozen(entry); Object.freeze(value); } return value; }
const request = createRuntimeAuthorityRequest({ requestId: "authority-4d5", subject: { subjectId: "director-1", subjectType: "director", tenantScope: "tenant-a", executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "agent", tenantScope: "tenant-a", executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executable: false, authoritative: false }, context: { correlationId: "correlation-4d5", timestamp: "2026-07-23T12:00:00.000Z", metadata: {}, executable: false, authoritative: false }, executable: false, authoritative: false });
const execution = { executionId: "execution-4d5", correlationId: "correlation-4d5", commandId: "agent.restart" as const, commandVersion: "1.0.0", targetIdentity: "agent-1", adapterFamily: "agent" as const, capability: "agent.lifecycle" as const, creationTimestamp: "2026-07-23T12:00:00.000Z", architectureVersion: "1.0.0" as const, executable: false as const, authoritative: false as const };
const identity = createAuthorityIdentityChain({ tenant: { tenantId: "tenant-a", tenantType: "organization", metadata: {}, executable: false, authoritative: false }, workspace: { workspaceId: "workspace-a", workspaceType: "workspace", tenantId: "tenant-a", metadata: {}, executable: false, authoritative: false }, principal: { principalId: "principal-a", principalType: "human", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, subject: { subjectId: "subject-a", subjectType: "authority_subject", principalId: "principal-a", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, delegations: [{ delegationId: "delegation-a", tenantId: "tenant-a", workspaceId: "workspace-a", delegatedByType: "human", delegatedById: "principal-a", agentId: "agent-1", metadata: {}, executable: false, authoritative: false }], agent: { agentId: "agent-1", agentType: "agent", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, execution: { executionIdentity: execution, authorityRequestId: "authority-4d5", tenantId: "tenant-a", workspaceId: "workspace-a", metadata: {}, executable: false, authoritative: false }, authorityRequest: request, executable: false, authoritative: false });
const policy = createRuntimePolicy({ metadata: { policyId: "policy-4d5", version: { value: "1.0.0", executable: false, authoritative: false }, metadata: {}, executable: false, authoritative: false }, subject: { identity, metadata: {}, executable: false, authoritative: false }, action: { actionId: "agent.restart", actionType: "lifecycle", executionId: "execution-4d5", metadata: {}, executable: false, authoritative: false }, resource: { resourceId: "agent-1", resourceType: "runtime_target", targetIdentity: "agent-1", metadata: {}, executable: false, authoritative: false }, environment: { environment: "production", metadata: {}, executable: false, authoritative: false }, conditions: [], effect: "approval_required", obligations: [], executable: false, authoritative: false });
const classification = createRuntimeRiskClassification({ metadata: { riskClassificationId: "risk-4d5", authorityRequestId: "authority-4d5", policyId: "policy-4d5", tenantId: "tenant-a", workspaceId: "workspace-a", executionId: "execution-4d5", actionId: "agent.restart", resourceId: "agent-1", version: { value: "1.0.0", executable: false, authoritative: false }, metadata: {}, executable: false, authoritative: false }, authorityRequest: request, policy, profile: { level: "high", domains: ["security"], impactScope: "workspace", blastRadius: "limited", reversibility: "compensatable", dataSensitivity: "restricted", sideEffects: ["internal_state_change"], factors: [], metadata: {}, executable: false, authoritative: false }, approval: { mode: "single_human", quorum: { requiredCount: 1, distinctApproversRequired: false, roles: [], orderingRequired: false, separationOfDutiesRequired: false, executable: false, authoritative: false }, constraints: [], metadata: {}, executable: false, authoritative: false }, executable: false, authoritative: false });
const input = { record: { metadata: { approvalId: "approval-4d5", authorityRequestId: "authority-4d5", riskClassificationId: "risk-4d5", version: { value: "1.0.0", executable: false as const, authoritative: false as const }, metadata: { labels: ["record"] }, executable: false as const, authoritative: false as const }, status: "approved" as const, decision: { value: "approve" as const, reason: "Reviewed manually.", executable: false as const, authoritative: false as const }, actor: { actorId: "approver-1", identity, metadata: {}, executable: false as const, authoritative: false as const }, evidence: [{ evidenceType: "ticket_reference" as const, reference: "TICKET-1", metadata: {}, executable: false as const, authoritative: false as const }], timestamp: { recordedAt: "2026-07-23T12:00:00.000Z", executable: false as const, authoritative: false as const }, executable: false as const, authoritative: false as const }, classification, executable: false as const, authoritative: false as const };
const approval = createRuntimeHumanApproval(input);
assert.equal(Object.isFrozen(approval), true); assert.equal(Object.isFrozen(approval.record.evidence), true); assert.equal(validateRuntimeHumanApproval(approval).status, "valid"); assert.equal(validateRuntimeHumanApprovalResult(approval).authoritative, false); assert.notEqual(approval.record.metadata.metadata, input.record.metadata.metadata); assert.deepEqual(RUNTIME_APPROVAL_STATUSES, ["pending", "approved", "rejected", "expired", "withdrawn"]); assert.deepEqual(RUNTIME_APPROVAL_DECISIONS, ["approve", "reject", "abstain"]);
assert.equal(validateRuntimeHumanApproval(createRuntimeHumanApproval({ ...input, record: { ...input.record, metadata: { ...input.record.metadata, authorityRequestId: "other" } } })).error?.code, "AUTHORITY_REQUEST_MISMATCH");
assert.equal(validateRuntimeHumanApproval(createRuntimeHumanApproval({ ...input, record: { ...input.record, metadata: { ...input.record.metadata, riskClassificationId: "other" } } })).error?.code, "APPROVAL_REQUIREMENT_MISMATCH");
assert.equal(validateRuntimeHumanApproval(createRuntimeHumanApproval({ ...input, record: { ...input.record, actor: { ...input.record.actor, identity: frozen({ ...identity, tenant: { ...identity.tenant, tenantId: "tenant-b" } }) } } } as never)).error?.code, "IDENTITY_MISMATCH");
assert.throws(() => createRuntimeHumanApproval({ ...input, record: { ...input.record, evidence: [{ ...input.record.evidence[0]!, metadata: { callback: () => undefined } }] } } as never));
assert.throws(() => createRuntimeHumanApproval({ ...input, record: { ...input.record, actor: { ...input.record.actor, metadata: { promise: Promise.resolve() } } } } as never));
assert.throws(() => createRuntimeHumanApproval({ ...input, record: { ...input.record, metadata: { ...input.record.metadata, metadata: { marker: Symbol("x") } } } } as never));
const cyclic: { self?: unknown } = {}; cyclic.self = cyclic;
assert.throws(() => createRuntimeHumanApproval({ ...input, record: { ...input.record, metadata: { ...input.record.metadata, metadata: cyclic } } } as never));
class ProviderLike { readonly name = "provider"; }
assert.throws(() => createRuntimeHumanApproval({ ...input, record: { ...input.record, actor: { ...input.record.actor, metadata: { provider: new ProviderLike() } } } } as never));
assert.throws(() => { (approval.record.metadata.metadata.labels as unknown as string[]).push("mutation"); });
console.log("runtime human approval checks passed");
