import type { Agent, Department } from "@/types";

export const agents: Agent[] = [
  {
    id: "agent-seo",
    name: "SEO Agent",
    role: "Search Optimization",
    department: "Marketing",
    status: "running",
    version: "v1.4.2",
    tasksToday: 32,
    costToday: 2.14,
    lastActive: "2m ago",
  },
  {
    id: "agent-sales",
    name: "Sales Agent",
    role: "Deal Execution",
    department: "Sales",
    status: "running",
    version: "v2.1.0",
    tasksToday: 18,
    costToday: 3.42,
    lastActive: "just now",
  },
  {
    id: "agent-support",
    name: "Support Agent",
    role: "Customer Support",
    department: "Operations",
    status: "running",
    version: "v1.9.1",
    tasksToday: 54,
    costToday: 1.87,
    lastActive: "1m ago",
  },
  {
    id: "agent-research",
    name: "Research Agent",
    role: "Market Research",
    department: "Research",
    status: "idle",
    version: "v1.2.0",
    tasksToday: 6,
    costToday: 0.92,
    lastActive: "26m ago",
  },
  {
    id: "agent-lead-qualifier",
    name: "Lead Qualifier Agent",
    role: "Lead Scoring",
    department: "Sales",
    status: "running",
    version: "v1.7.3",
    tasksToday: 41,
    costToday: 1.65,
    lastActive: "just now",
  },
  {
    id: "agent-proposal",
    name: "Proposal Agent",
    role: "Proposal Drafting",
    department: "Sales",
    status: "paused",
    version: "v1.1.0",
    tasksToday: 4,
    costToday: 0.58,
    lastActive: "1h ago",
  },
  {
    id: "agent-negotiation",
    name: "Negotiation Agent",
    role: "Deal Negotiation",
    department: "Sales",
    status: "error",
    version: "v0.9.4",
    tasksToday: 2,
    costToday: 0.31,
    lastActive: "3h ago",
  },
  {
    id: "agent-customer-success",
    name: "Customer Success Agent",
    role: "Customer Success",
    department: "Sales",
    status: "running",
    version: "v1.0.2",
    tasksToday: 12,
    costToday: 0.74,
    lastActive: "5m ago",
  },
  {
    id: "agent-renewal",
    name: "Renewal Agent",
    role: "Renewal Management",
    department: "Sales",
    status: "idle",
    version: "v0.8.0",
    tasksToday: 3,
    costToday: 0.22,
    lastActive: "2h ago",
  },
  {
    id: "agent-ticket-management",
    name: "Ticket Management Agent",
    role: "Ticket Routing & Triage",
    department: "Operations",
    status: "running",
    version: "v1.3.1",
    tasksToday: 61,
    costToday: 1.12,
    lastActive: "just now",
  },
  {
    id: "agent-knowledge-base",
    name: "Knowledge Base Agent",
    role: "Knowledge Curation",
    department: "Operations",
    status: "running",
    version: "v1.0.0",
    tasksToday: 9,
    costToday: 0.41,
    lastActive: "12m ago",
  },
  {
    id: "agent-finance",
    name: "Finance Agent",
    role: "Finance Department Manager",
    department: "Finance",
    status: "running",
    version: "v1.0.0",
    tasksToday: 14,
    costToday: 0.88,
    lastActive: "just now",
  },
  {
    id: "agent-invoice",
    name: "Invoice Agent",
    role: "Invoice Lifecycle",
    department: "Finance",
    status: "running",
    version: "v1.1.0",
    tasksToday: 27,
    costToday: 0.63,
    lastActive: "3m ago",
  },
  {
    id: "agent-payment",
    name: "Payment Agent",
    role: "Payment Verification",
    department: "Finance",
    status: "running",
    version: "v1.0.4",
    tasksToday: 19,
    costToday: 0.71,
    lastActive: "just now",
  },
  {
    id: "agent-budget",
    name: "Budget Agent",
    role: "Budget Monitoring",
    department: "Finance",
    status: "running",
    version: "v0.9.2",
    tasksToday: 8,
    costToday: 0.34,
    lastActive: "18m ago",
  },
  {
    id: "agent-expense",
    name: "Expense Agent",
    role: "Expense Categorization",
    department: "Finance",
    status: "running",
    version: "v1.0.1",
    tasksToday: 41,
    costToday: 0.52,
    lastActive: "1m ago",
  },
  {
    id: "agent-cash-flow",
    name: "Cash Flow Agent",
    role: "Cash Flow Monitoring",
    department: "Finance",
    status: "running",
    version: "v0.8.0",
    tasksToday: 6,
    costToday: 0.29,
    lastActive: "24m ago",
  },
  {
    id: "agent-financial-analytics",
    name: "Financial Analytics Agent",
    role: "Financial Analytics",
    department: "Finance",
    status: "idle",
    version: "v0.7.3",
    tasksToday: 3,
    costToday: 0.44,
    lastActive: "1h ago",
  },
  {
    id: "agent-tax",
    name: "Tax Agent",
    role: "Tax & Compliance",
    department: "Finance",
    status: "paused",
    version: "v0.6.0",
    tasksToday: 2,
    costToday: 0.19,
    lastActive: "3h ago",
  },
  {
    id: "agent-hr",
    name: "HR Agent",
    role: "HR Department Manager",
    department: "HR",
    status: "running",
    version: "v1.0.0",
    tasksToday: 11,
    costToday: 0.62,
    lastActive: "just now",
  },
  {
    id: "agent-recruiting",
    name: "Recruiting Agent",
    role: "Talent Sourcing",
    department: "HR",
    status: "running",
    version: "v1.1.0",
    tasksToday: 23,
    costToday: 0.58,
    lastActive: "2m ago",
  },
  {
    id: "agent-candidate-screening",
    name: "Candidate Screening Agent",
    role: "Candidate Screening",
    department: "HR",
    status: "running",
    version: "v1.0.3",
    tasksToday: 34,
    costToday: 0.71,
    lastActive: "just now",
  },
  {
    id: "agent-interview-scheduling",
    name: "Interview Scheduling Agent",
    role: "Interview Coordination",
    department: "HR",
    status: "running",
    version: "v1.0.1",
    tasksToday: 17,
    costToday: 0.29,
    lastActive: "6m ago",
  },
  {
    id: "agent-onboarding",
    name: "Onboarding Agent",
    role: "Employee Onboarding",
    department: "HR",
    status: "running",
    version: "v0.9.0",
    tasksToday: 8,
    costToday: 0.34,
    lastActive: "21m ago",
  },
  {
    id: "agent-performance-review",
    name: "Performance Review Agent",
    role: "Performance Reviews",
    department: "HR",
    status: "idle",
    version: "v0.8.2",
    tasksToday: 5,
    costToday: 0.27,
    lastActive: "1h ago",
  },
  {
    id: "agent-learning-development",
    name: "Learning & Development Agent",
    role: "Learning & Development",
    department: "HR",
    status: "running",
    version: "v0.9.1",
    tasksToday: 12,
    costToday: 0.4,
    lastActive: "9m ago",
  },
  {
    id: "agent-employee-support",
    name: "Employee Support Agent",
    role: "Employee Support",
    department: "HR",
    status: "running",
    version: "v1.0.0",
    tasksToday: 29,
    costToday: 0.46,
    lastActive: "1m ago",
  },
  {
    id: "agent-offboarding",
    name: "Offboarding Agent",
    role: "Employee Offboarding",
    department: "HR",
    status: "paused",
    version: "v0.7.0",
    tasksToday: 2,
    costToday: 0.15,
    lastActive: "4h ago",
  },
  {
    id: "agent-legal",
    name: "Legal Agent",
    role: "Legal Department Manager",
    department: "Legal",
    status: "running",
    version: "v1.0.0",
    tasksToday: 9,
    costToday: 0.71,
    lastActive: "just now",
  },
  {
    id: "agent-contract-review",
    name: "Contract Review Agent",
    role: "Contract Review",
    department: "Legal",
    status: "running",
    version: "v1.1.0",
    tasksToday: 18,
    costToday: 0.94,
    lastActive: "3m ago",
  },
  {
    id: "agent-contract-generation",
    name: "Contract Generation Agent",
    role: "Contract Drafting",
    department: "Legal",
    status: "running",
    version: "v1.0.2",
    tasksToday: 12,
    costToday: 0.66,
    lastActive: "8m ago",
  },
  {
    id: "agent-compliance",
    name: "Compliance Agent",
    role: "Compliance Monitoring",
    department: "Legal",
    status: "running",
    version: "v1.0.1",
    tasksToday: 21,
    costToday: 0.58,
    lastActive: "just now",
  },
  {
    id: "agent-risk-assessment",
    name: "Risk Assessment Agent",
    role: "Risk Assessment",
    department: "Legal",
    status: "running",
    version: "v0.9.0",
    tasksToday: 14,
    costToday: 0.49,
    lastActive: "14m ago",
  },
  {
    id: "agent-policy-management",
    name: "Policy Management Agent",
    role: "Policy Management",
    department: "Legal",
    status: "idle",
    version: "v0.8.1",
    tasksToday: 6,
    costToday: 0.31,
    lastActive: "1h ago",
  },
  {
    id: "agent-regulatory-monitoring",
    name: "Regulatory Monitoring Agent",
    role: "Regulatory Monitoring",
    department: "Legal",
    status: "running",
    version: "v0.9.2",
    tasksToday: 10,
    costToday: 0.42,
    lastActive: "22m ago",
  },
  {
    id: "agent-ip-trademark",
    name: "IP & Trademark Agent",
    role: "IP & Trademark",
    department: "Legal",
    status: "paused",
    version: "v0.7.0",
    tasksToday: 3,
    costToday: 0.18,
    lastActive: "5h ago",
  },
];

export const departments: Department[] = [
  {
    id: "dept-marketing",
    name: "Marketing",
    headAgent: "SEO Agent",
    agents: ["SEO Agent"],
  },
  {
    id: "dept-sales",
    name: "Sales",
    headAgent: "Sales Agent",
    agents: [
      "Sales Agent",
      "Lead Qualifier Agent",
      "Proposal Agent",
      "Negotiation Agent",
      "Customer Success Agent",
      "Renewal Agent",
    ],
  },
  {
    id: "dept-operations",
    name: "Operations",
    headAgent: "Support Agent",
    agents: ["Support Agent", "Ticket Management Agent", "Knowledge Base Agent"],
  },
  {
    id: "dept-finance",
    name: "Finance",
    headAgent: "Finance Agent",
    agents: [
      "Finance Agent",
      "Invoice Agent",
      "Payment Agent",
      "Budget Agent",
      "Expense Agent",
      "Cash Flow Agent",
      "Financial Analytics Agent",
      "Tax Agent",
    ],
  },
  {
    id: "dept-hr",
    name: "HR",
    headAgent: "HR Agent",
    agents: [
      "HR Agent",
      "Recruiting Agent",
      "Candidate Screening Agent",
      "Interview Scheduling Agent",
      "Onboarding Agent",
      "Performance Review Agent",
      "Learning & Development Agent",
      "Employee Support Agent",
      "Offboarding Agent",
    ],
  },
  {
    id: "dept-legal",
    name: "Legal",
    headAgent: "Legal Agent",
    agents: [
      "Legal Agent",
      "Contract Review Agent",
      "Contract Generation Agent",
      "Compliance Agent",
      "Risk Assessment Agent",
      "Policy Management Agent",
      "Regulatory Monitoring Agent",
      "IP & Trademark Agent",
    ],
  },
  {
    id: "dept-research",
    name: "Research",
    headAgent: "Research Agent",
    agents: ["Research Agent"],
  },
];
