import type { SystemEvent } from "@/types";

export const events: SystemEvent[] = [
  {
    id: "evt-s01",
    type: "sla.warning",
    source: "Ticket Management Agent",
    message: "Ticket #4830 approaching SLA limit — 22 minutes left",
    severity: "warning",
    timestamp: "just now",
  },
  {
    id: "evt-s02",
    type: "ticket.assigned",
    source: "Ticket Management Agent",
    message: "Ticket #4831 routed to Support Agent",
    severity: "info",
    timestamp: "1m ago",
  },
  {
    id: "evt-s03",
    type: "renewal.won",
    source: "Renewal Agent",
    message: "Contoso Ltd renewed annual plan — $12,400 ARR retained",
    severity: "success",
    timestamp: "6m ago",
  },
  {
    id: "evt-s04",
    type: "proposal.created",
    source: "Proposal Agent",
    message: "Proposal drafted for Acme GmbH — awaiting internal review",
    severity: "info",
    timestamp: "11m ago",
  },
  {
    id: "evt-s05",
    type: "negotiation.started",
    source: "Negotiation Agent",
    message: "Negotiation opened with Northwind — target close in 5 days",
    severity: "info",
    timestamp: "18m ago",
  },
  {
    id: "evt-s06",
    type: "sla.breached",
    source: "Ticket Management Agent",
    message: "Ticket #4802 breached 4h SLA — escalated to Director Inbox",
    severity: "error",
    timestamp: "34m ago",
  },
  {
    id: "evt-s07",
    type: "issue.resolved",
    source: "Support Agent",
    message: "Ticket #4818 resolved — customer confirmed fix",
    severity: "success",
    timestamp: "48m ago",
  },
  {
    id: "evt-s08",
    type: "knowledge.updated",
    source: "Knowledge Base Agent",
    message: "Article 'Refund policy for annual plans' rewritten from 3 resolved tickets",
    severity: "info",
    timestamp: "1h ago",
  },
  {
    id: "evt-s09",
    type: "renewal.due",
    source: "Renewal Agent",
    message: "Globex contract renews in 14 days — health score 71, outreach scheduled",
    severity: "warning",
    timestamp: "2h ago",
  },
  {
    id: "evt-s10",
    type: "support.request",
    source: "Gmail",
    message: "New support request from fabrikam.com — ticket #4832 created",
    severity: "info",
    timestamp: "2h ago",
  },
  {
    id: "evt-s11",
    type: "renewal.lost",
    source: "Renewal Agent",
    message: "Initech churned — exit survey queued, $3,600 ARR lost",
    severity: "error",
    timestamp: "4h ago",
  },
  {
    id: "evt-001",
    type: "workflow.completed",
    source: "Customer Support",
    message: "Ticket #4821 resolved and customer notified",
    severity: "success",
    timestamp: "just now",
  },
  {
    id: "evt-002",
    type: "lead.qualified",
    source: "Lead Qualifier Agent",
    message: "Acme GmbH scored 87 — moved to qualified",
    severity: "info",
    timestamp: "2m ago",
  },
  {
    id: "evt-003",
    type: "approval.requested",
    source: "Sales Agent",
    message: "18% discount for Northwind deal awaits Director approval",
    severity: "warning",
    timestamp: "9m ago",
  },
  {
    id: "evt-004",
    type: "deploy.succeeded",
    source: "Vercel",
    message: "hebun-dashboard deployed to production",
    severity: "success",
    timestamp: "14m ago",
  },
  {
    id: "evt-005",
    type: "agent.error",
    source: "Negotiation Agent",
    message: "Rate limit exceeded on outbound email — run halted",
    severity: "error",
    timestamp: "42m ago",
  },
  {
    id: "evt-006",
    type: "github.push",
    source: "GitHub",
    message: "3 commits pushed to hebun-ai/dashboard main",
    severity: "info",
    timestamp: "1h ago",
  },
  {
    id: "evt-007",
    type: "memory.updated",
    source: "Research Agent",
    message: "Q3 market analysis written to company memory",
    severity: "info",
    timestamp: "2h ago",
  },
  {
    id: "evt-008",
    type: "workflow.failed",
    source: "Approval Review",
    message: "Step 3 (notify Director) timed out after retries",
    severity: "error",
    timestamp: "42m ago",
  },
  {
    id: "evt-009",
    type: "integration.synced",
    source: "Gmail",
    message: "Inbox sync completed — 12 new threads indexed",
    severity: "success",
    timestamp: "3h ago",
  },
  {
    id: "evt-010",
    type: "agent.created",
    source: "Agent Registry",
    message: "Proposal Agent v1.1.0 registered and pending approval",
    severity: "info",
    timestamp: "5h ago",
  },
];
