import type { DirectorCommandDefinition } from "./types";
import { deepFreeze } from "./validation";

export const COMMAND_DEFINITION_VERSION = "1.0.0";

/**
 * The declared Director commands.
 *
 * Each entry is inert data describing what a command would mean. None of them
 * can run: there is no executor, and definitions carry no behaviour.
 */
export const DIRECTOR_COMMAND_DEFINITIONS: readonly DirectorCommandDefinition[] = deepFreeze([
  {
    commandId: "agent.restart",
    version: COMMAND_DEFINITION_VERSION,
    label: "Restart Agent",
    description: "Restart an active agent so it resumes from a clean runtime state.",
    category: "lifecycle",
    risk: "high",
    safety: {
      riskLevel: "high",
      category: "operational",
      confirmationRequired: true,
      userImpact: "limited",
      systemImpact: "localized",
      estimatedEffect: "Restarts one active agent from a clean runtime state.",
      rollbackAvailability: "unavailable",
      auditRequired: true,
    },
    targetSectionId: "active-agents",
    permission: { capability: "agent.lifecycle", minimumPrivilege: "high", requiresApproval: true },
    executable: false,
  },
  {
    commandId: "workflow.retry",
    version: COMMAND_DEFINITION_VERSION,
    label: "Retry Workflow",
    description: "Re-run a workflow that finished in a failed state.",
    category: "recovery",
    risk: "high",
    safety: {
      riskLevel: "high",
      category: "recovery",
      confirmationRequired: true,
      userImpact: "material",
      systemImpact: "localized",
      estimatedEffect: "Re-runs one workflow that previously finished in a failed state.",
      rollbackAvailability: "unavailable",
      auditRequired: true,
    },
    targetSectionId: "active-workflows",
    permission: { capability: "workflow.recovery", minimumPrivilege: "high", requiresApproval: true },
    executable: false,
  },
  {
    commandId: "workflow.pause",
    version: COMMAND_DEFINITION_VERSION,
    label: "Pause Workflow",
    description: "Hold a running workflow at its current step without cancelling it.",
    category: "lifecycle",
    risk: "medium",
    safety: {
      riskLevel: "medium",
      category: "operational",
      confirmationRequired: true,
      userImpact: "limited",
      systemImpact: "localized",
      estimatedEffect: "Holds one running workflow at its current step.",
      rollbackAvailability: "available",
      auditRequired: true,
    },
    targetSectionId: "active-workflows",
    permission: { capability: "workflow.lifecycle", minimumPrivilege: "medium", requiresApproval: true },
    executable: false,
  },
  {
    commandId: "workflow.resume",
    version: COMMAND_DEFINITION_VERSION,
    label: "Resume Workflow",
    description: "Release a paused workflow so it continues from where it stopped.",
    category: "lifecycle",
    risk: "medium",
    safety: {
      riskLevel: "medium",
      category: "operational",
      confirmationRequired: true,
      userImpact: "limited",
      systemImpact: "localized",
      estimatedEffect: "Continues one paused workflow from its current step.",
      rollbackAvailability: "available",
      auditRequired: true,
    },
    targetSectionId: "active-workflows",
    permission: { capability: "workflow.lifecycle", minimumPrivilege: "medium", requiresApproval: false },
    executable: false,
  },
  {
    commandId: "diagnostics.re-evaluate",
    version: COMMAND_DEFINITION_VERSION,
    label: "Re-evaluate Diagnostics",
    description: "Rebuild diagnostics projections from the signals already collected.",
    category: "observability",
    risk: "low",
    safety: {
      riskLevel: "low",
      category: "observability",
      confirmationRequired: false,
      userImpact: "none",
      systemImpact: "none",
      estimatedEffect: "Rebuilds diagnostics projections from already collected signals.",
      rollbackAvailability: "not-applicable",
      auditRequired: false,
    },
    targetSectionId: "diagnostics-summary",
    permission: { capability: "observability.reevaluate", minimumPrivilege: "baseline", requiresApproval: false },
    executable: false,
  },
  {
    commandId: "monitoring.refresh",
    version: COMMAND_DEFINITION_VERSION,
    label: "Refresh Monitoring",
    description: "Recompute monitoring aggregates from the signals already collected.",
    category: "observability",
    risk: "low",
    safety: {
      riskLevel: "low",
      category: "observability",
      confirmationRequired: false,
      userImpact: "none",
      systemImpact: "none",
      estimatedEffect: "Recomputes monitoring aggregates from already collected signals.",
      rollbackAvailability: "not-applicable",
      auditRequired: false,
    },
    targetSectionId: "monitoring-summary",
    permission: { capability: "observability.reevaluate", minimumPrivilege: "baseline", requiresApproval: false },
    executable: false,
  },
]);
