import type { AuthorityIdentityChain } from "./runtime-authority-identity";
import type { RuntimeRiskClassification } from "./runtime-risk-classification";
import { deepFreeze, validText } from "./validation";

export const RUNTIME_HUMAN_APPROVAL_VERSION = "runtime-human-approval/v1";
export const RUNTIME_APPROVAL_STATUSES = ["pending", "approved", "rejected", "expired", "withdrawn"] as const;
export const RUNTIME_APPROVAL_DECISIONS = ["approve", "reject", "abstain"] as const;
export const RUNTIME_HUMAN_APPROVAL_ERROR_CODES = ["INVALID_APPROVAL", "INVALID_APPROVAL_STATUS", "INVALID_APPROVAL_DECISION", "INVALID_APPROVAL_ACTOR", "INVALID_APPROVAL_EVIDENCE", "APPROVAL_REQUIREMENT_MISMATCH", "AUTHORITY_REQUEST_MISMATCH", "IDENTITY_MISMATCH", "EXECUTABLE_VALUE_LEAKAGE", "APPROVAL_SERIALIZATION_FAILED"] as const;
type Metadata = string | number | boolean | null | readonly Metadata[] | { readonly [key: string]: Metadata }; type ErrorCode = (typeof RUNTIME_HUMAN_APPROVAL_ERROR_CODES)[number];
export interface RuntimeApprovalVersion { readonly value: string; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalTimestamp { readonly recordedAt: string; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalActor { readonly actorId: string; readonly identity: AuthorityIdentityChain; readonly metadata: Readonly<Record<string, Metadata>>; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalEvidence { readonly evidenceType: "justification" | "ticket_reference" | "document_reference" | "change_request" | "audit_reference"; readonly reference: string; readonly metadata: Readonly<Record<string, Metadata>>; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalDecision { readonly value: (typeof RUNTIME_APPROVAL_DECISIONS)[number]; readonly reason: string; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalMetadata { readonly approvalId: string; readonly authorityRequestId: string; readonly riskClassificationId: string; readonly version: RuntimeApprovalVersion; readonly metadata: Readonly<Record<string, Metadata>>; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalRecord { readonly metadata: RuntimeApprovalMetadata; readonly status: (typeof RUNTIME_APPROVAL_STATUSES)[number]; readonly decision: RuntimeApprovalDecision; readonly actor: RuntimeApprovalActor; readonly evidence: readonly RuntimeApprovalEvidence[]; readonly timestamp: RuntimeApprovalTimestamp; readonly executable: false; readonly authoritative: false; }
export interface RuntimeHumanApproval { readonly record: RuntimeApprovalRecord; readonly classification: RuntimeRiskClassification; readonly architectureVersion: typeof RUNTIME_HUMAN_APPROVAL_VERSION; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalValidationError { readonly code: ErrorCode; readonly message: string; }
export interface RuntimeApprovalValidation { readonly status: "valid" | "invalid"; readonly error?: RuntimeApprovalValidationError; readonly executable: false; readonly authoritative: false; }
export interface RuntimeApprovalValidationResult { readonly approval: RuntimeHumanApproval; readonly validation: RuntimeApprovalValidation; readonly executable: false; readonly authoritative: false; }
function copy(value: unknown, seen = new WeakSet<object>()): Metadata { if (value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean") return value; if (!value || typeof value !== "object" || value instanceof Promise || seen.has(value) || (Object.getPrototypeOf(value) !== Object.prototype && !Array.isArray(value))) throw new TypeError("Approval metadata must be serializable inert data."); seen.add(value); return Array.isArray(value) ? value.map((v) => copy(v, seen)) : Object.fromEntries(Object.entries(value).map(([k, v]) => [k, copy(v, seen)])); }
function inert(value: unknown): value is { readonly executable: false; readonly authoritative: false } { return Boolean(value) && typeof value === "object" && Object.isFrozen(value) && (value as { executable?: unknown }).executable === false && (value as { authoritative?: unknown }).authoritative === false; }
function invalid(code: ErrorCode, message: string): RuntimeApprovalValidation { return deepFreeze({ status: "invalid" as const, error: { code, message }, executable: false as const, authoritative: false as const }); }
/** Copies a descriptive approval record. An approved record never becomes an execution permit. */
export function createRuntimeHumanApproval(input: Omit<RuntimeHumanApproval, "architectureVersion">): RuntimeHumanApproval { const copied = copy(input) as unknown as Omit<RuntimeHumanApproval, "architectureVersion">; const r = copied.record; const values = [copied, r, r.metadata, r.metadata.version, r.decision, r.actor, r.actor.identity, r.timestamp, copied.classification, ...r.evidence]; if (values.some((v) => !v || (v as { executable?: unknown }).executable !== false || (v as { authoritative?: unknown }).authoritative !== false)) throw new TypeError("Invalid Runtime Human Approval."); return deepFreeze({ ...copied, record: { ...r, metadata: { ...r.metadata, version: { ...r.metadata.version }, metadata: r.metadata.metadata }, decision: { ...r.decision }, actor: { ...r.actor, identity: r.actor.identity, metadata: r.actor.metadata }, evidence: r.evidence.map((e) => ({ ...e, metadata: e.metadata })), timestamp: { ...r.timestamp } }, classification: copied.classification, architectureVersion: RUNTIME_HUMAN_APPROVAL_VERSION, executable: false as const, authoritative: false as const }); }
/** Validates record linkage only; it never satisfies a requirement or authorizes Runtime. */
export function validateRuntimeHumanApproval(value: RuntimeHumanApproval): RuntimeApprovalValidation { const r = value.record; const values = [value, r, r.metadata, r.metadata.version, r.decision, r.actor, r.actor.identity, r.timestamp, value.classification, ...r.evidence]; if (values.some((v) => !inert(v))) return invalid("EXECUTABLE_VALUE_LEAKAGE", "Approval must be immutable inert metadata."); try { JSON.stringify(value); } catch { return invalid("APPROVAL_SERIALIZATION_FAILED", "Approval is not serializable."); } if (![r.metadata.approvalId, r.metadata.authorityRequestId, r.metadata.riskClassificationId, r.metadata.version.value, r.actor.actorId, r.timestamp.recordedAt].every(validText)) return invalid("INVALID_APPROVAL", "Approval metadata is invalid."); if (!(RUNTIME_APPROVAL_STATUSES as readonly string[]).includes(r.status)) return invalid("INVALID_APPROVAL_STATUS", "Approval status is invalid."); if (!(RUNTIME_APPROVAL_DECISIONS as readonly string[]).includes(r.decision.value) || !validText(r.decision.reason)) return invalid("INVALID_APPROVAL_DECISION", "Approval decision is invalid."); const actorChain = r.actor.identity; const requestChain = value.classification.policy.subject.identity; if (!actorChain || actorChain.tenant?.tenantId !== requestChain.tenant?.tenantId || actorChain.workspace?.workspaceId !== requestChain.workspace?.workspaceId || actorChain.execution?.executionIdentity?.executionId !== requestChain.execution?.executionIdentity?.executionId) return invalid("IDENTITY_MISMATCH", "Approval actor must reference the classification identity chain."); if (r.metadata.authorityRequestId !== value.classification.metadata.authorityRequestId || r.metadata.authorityRequestId !== value.classification.authorityRequest.requestId) return invalid("AUTHORITY_REQUEST_MISMATCH", "Authority Request binding is invalid."); if (r.metadata.riskClassificationId !== value.classification.metadata.riskClassificationId || !value.classification.approval) return invalid("APPROVAL_REQUIREMENT_MISMATCH", "Approval requirement binding is invalid."); if (!r.evidence.every((e) => ["justification", "ticket_reference", "document_reference", "change_request", "audit_reference"].includes(e.evidenceType) && validText(e.reference))) return invalid("INVALID_APPROVAL_EVIDENCE", "Approval evidence is invalid."); return deepFreeze({ status: "valid" as const, executable: false as const, authoritative: false as const }); }
export function validateRuntimeHumanApprovalResult(approval: RuntimeHumanApproval): RuntimeApprovalValidationResult { return deepFreeze({ approval, validation: validateRuntimeHumanApproval(approval), executable: false as const, authoritative: false as const }); }
