import { deepFreeze } from "./validation";
export const RUNTIME_SAFETY_CLASSIFICATIONS = ["safe", "elevated", "critical", "blocked"] as const;
export type RuntimeSafetyClassification = (typeof RUNTIME_SAFETY_CLASSIFICATIONS)[number];
export const RUNTIME_EXECUTION_READINESS_STATES = ["ready", "not_ready", "blocked", "authority_required"] as const;
export type RuntimeExecutionReadinessState = (typeof RUNTIME_EXECUTION_READINESS_STATES)[number];
export const RUNTIME_TIMEOUT_CLASSES = ["none", "bounded", "manual"] as const;
export const RUNTIME_CANCELLATION_POLICIES = ["cancellable", "non_cancellable"] as const;
export const RUNTIME_ROLLBACK_CLASSIFICATIONS = ["none", "compensating_action", "transactional", "manual_recovery"] as const;
export const RUNTIME_SAFETY_ERROR_CODES = ["SAFETY_POLICY_MISSING", "EXECUTION_NOT_READY", "AUTHORITY_REQUIRED", "PRECONDITION_FAILED", "INVALID_TIMEOUT_POLICY", "INVALID_CANCELLATION_POLICY", "INVALID_ROLLBACK_POLICY", "INVALID_FAIL_CLOSED_POLICY", "SAFETY_CLASSIFICATION_MISMATCH"] as const;
export interface RuntimeSafetyPreconditions { readonly authorityRequired: true; readonly adapterAvailable: true; readonly targetResolved: true; readonly capabilityValid: true; readonly safetyPolicyPresent: true; }
export interface RuntimeSafetyPolicy { readonly classification: RuntimeSafetyClassification; readonly preconditions: RuntimeSafetyPreconditions; readonly timeout: { readonly required: true; readonly timeoutClass: (typeof RUNTIME_TIMEOUT_CLASSES)[number]; readonly strategy: "future-runtime" }; readonly cancellation: { readonly policy: (typeof RUNTIME_CANCELLATION_POLICIES)[number]; readonly strategy: "future-runtime" }; readonly rollback: (typeof RUNTIME_ROLLBACK_CLASSIFICATIONS)[number]; readonly failClosed: { readonly denyOnUncertainty: true; readonly denyOnMissingAuthority: true; readonly denyOnInconsistentMetadata: true; readonly denyOnUnsupportedAdapter: true; }; readonly executable: false; readonly authoritative: false; }
export type RuntimeSafetyValidation = { readonly status: "blocked" | "invalid"; readonly readiness: RuntimeExecutionReadinessState; readonly executable: false; readonly authoritative: false; readonly error?: { readonly code: (typeof RUNTIME_SAFETY_ERROR_CODES)[number]; readonly message: string; } };
export function createRuntimeSafetyPolicy(input: { readonly classification: RuntimeSafetyClassification; readonly cancellation: (typeof RUNTIME_CANCELLATION_POLICIES)[number]; readonly rollback: (typeof RUNTIME_ROLLBACK_CLASSIFICATIONS)[number]; }): RuntimeSafetyPolicy { return deepFreeze({ classification: input.classification, preconditions: { authorityRequired: true, adapterAvailable: true, targetResolved: true, capabilityValid: true, safetyPolicyPresent: true }, timeout: { required: true, timeoutClass: "bounded", strategy: "future-runtime" }, cancellation: { policy: input.cancellation, strategy: "future-runtime" }, rollback: input.rollback, failClosed: { denyOnUncertainty: true, denyOnMissingAuthority: true, denyOnInconsistentMetadata: true, denyOnUnsupportedAdapter: true }, executable: false, authoritative: false }); }
export function validateRuntimeSafetyPolicy(policy: RuntimeSafetyPolicy): RuntimeSafetyValidation { const invalid = (code: (typeof RUNTIME_SAFETY_ERROR_CODES)[number], message: string) => deepFreeze({ status: "invalid" as const, readiness: "blocked" as const, executable: false as const, authoritative: false as const, error: { code, message } }); if (!Object.isFrozen(policy) || !Object.isFrozen(policy.preconditions) || !Object.isFrozen(policy.timeout) || !Object.isFrozen(policy.cancellation) || !Object.isFrozen(policy.failClosed) || policy.executable !== false || policy.authoritative !== false) return invalid("SAFETY_POLICY_MISSING", "Safety policy must be immutable."); if (!(RUNTIME_TIMEOUT_CLASSES as readonly string[]).includes(policy.timeout.timeoutClass) || policy.timeout.required !== true || policy.timeout.strategy !== "future-runtime") return invalid("INVALID_TIMEOUT_POLICY", "Timeout policy is invalid."); if (!(RUNTIME_CANCELLATION_POLICIES as readonly string[]).includes(policy.cancellation.policy) || policy.cancellation.strategy !== "future-runtime") return invalid("INVALID_CANCELLATION_POLICY", "Cancellation policy is invalid."); if (!(RUNTIME_ROLLBACK_CLASSIFICATIONS as readonly string[]).includes(policy.rollback)) return invalid("INVALID_ROLLBACK_POLICY", "Rollback policy is invalid."); if (!Object.values(policy.failClosed).every((value) => value === true)) return invalid("INVALID_FAIL_CLOSED_POLICY", "Fail-closed policy is invalid."); return deepFreeze({ status: "blocked" as const, readiness: "authority_required" as const, executable: false as const, authoritative: false as const }); }
