import type { RuntimeExecutionPermit } from "./runtime-execution-permit";
import { deepFreeze, validText } from "./validation";

export const RUNTIME_EXECUTION_PERMIT_LIFECYCLE_VERSION = "runtime-execution-permit-lifecycle/v1";
export const RUNTIME_PERMIT_LIFECYCLE_STATES = ["issued", "expired", "revoked"] as const;
export const RUNTIME_PERMIT_LIFECYCLE_ERROR_CODES = ["INVALID_TRANSITION", "TERMINAL_STATE", "INVALID_LIFECYCLE", "INVALID_REFERENCE", "SERIALIZATION_FAILED", "IMMUTABILITY_VIOLATION"] as const;
type Metadata = string | number | boolean | null | readonly Metadata[] | { readonly [key: string]: Metadata };
type State = (typeof RUNTIME_PERMIT_LIFECYCLE_STATES)[number];
type ErrorCode = (typeof RUNTIME_PERMIT_LIFECYCLE_ERROR_CODES)[number];
export interface RuntimePermitLifecycleState { readonly value: State; readonly recordedAt: string; readonly executable: false; readonly authoritative: false; }
export interface RuntimePermitLifecycleTransition { readonly from: State; readonly to: State; readonly occurredAt: string; readonly reference: string; readonly metadata: Readonly<Record<string, Metadata>>; readonly executable: false; readonly authoritative: false; }
export interface RuntimePermitLifecycleMetadata { readonly lifecycleId: string; readonly permitId: string; readonly schemaVersion: string; readonly version: string; readonly metadata: Readonly<Record<string, Metadata>>; readonly executable: false; readonly authoritative: false; }
export interface RuntimeExecutionPermitLifecycle { readonly permit: RuntimeExecutionPermit; readonly state: RuntimePermitLifecycleState; readonly transitions: readonly RuntimePermitLifecycleTransition[]; readonly metadata: RuntimePermitLifecycleMetadata; readonly architectureVersion: typeof RUNTIME_EXECUTION_PERMIT_LIFECYCLE_VERSION; readonly executable: false; readonly authoritative: false; }
export interface RuntimePermitLifecycleError { readonly code: ErrorCode; readonly message: string; }
export interface RuntimePermitLifecycleValidation { readonly status: "valid" | "invalid"; readonly error?: RuntimePermitLifecycleError; readonly executable: false; readonly authoritative: false; }
function copy(value: unknown, ancestors = new WeakSet<object>()): Metadata { if (value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean") return value; if (!value || typeof value !== "object" || value instanceof Promise || ancestors.has(value) || (Object.getPrototypeOf(value) !== Object.prototype && !Array.isArray(value))) throw new TypeError("Permit lifecycle metadata must be serializable inert data."); ancestors.add(value); const copied = Array.isArray(value) ? value.map((entry) => copy(entry, ancestors)) : Object.fromEntries(Object.entries(value).map(([key, entry]) => [key, copy(entry, ancestors)])); ancestors.delete(value); return copied; }
function inert(value: unknown): value is { readonly executable: false; readonly authoritative: false } { return Boolean(value) && typeof value === "object" && Object.isFrozen(value) && (value as { executable?: unknown }).executable === false && (value as { authoritative?: unknown }).authoritative === false; }
function invalid(code: ErrorCode, message: string): RuntimePermitLifecycleValidation { return deepFreeze({ status: "invalid" as const, error: { code, message }, executable: false as const, authoritative: false as const }); }
function legal(from: State, to: State): boolean { return from === "issued" && (to === "expired" || to === "revoked"); }
/** Copies lifecycle evidence only; it does not mutate or reissue the referenced permit. */
export function createRuntimeExecutionPermitLifecycle(input: Omit<RuntimeExecutionPermitLifecycle, "architectureVersion">): RuntimeExecutionPermitLifecycle { const copied = copy(input) as unknown as Omit<RuntimeExecutionPermitLifecycle, "architectureVersion">; const values = [copied, copied.permit, copied.state, copied.metadata, ...copied.transitions]; if (values.some((value) => !value || (value as { executable?: unknown }).executable !== false || (value as { authoritative?: unknown }).authoritative !== false)) throw new TypeError("Invalid Runtime Execution Permit Lifecycle."); return deepFreeze({ ...copied, state: { ...copied.state }, transitions: copied.transitions.map((transition) => ({ ...transition, metadata: transition.metadata })), metadata: { ...copied.metadata, metadata: copied.metadata.metadata }, architectureVersion: RUNTIME_EXECUTION_PERMIT_LIFECYCLE_VERSION, executable: false as const, authoritative: false as const }); }
/** Validates immutable lifecycle sequencing only; it never evaluates a permit prerequisite or Runtime behavior. */
export function validateRuntimeExecutionPermitLifecycle(value: RuntimeExecutionPermitLifecycle): RuntimePermitLifecycleValidation { const values = [value, value.permit, value.state, value.metadata, ...value.transitions]; if (values.some((entry) => !inert(entry))) return invalid("IMMUTABILITY_VIOLATION", "Lifecycle must be immutable inert metadata."); try { JSON.stringify(value); } catch { return invalid("SERIALIZATION_FAILED", "Lifecycle is not serializable."); } if (![value.metadata.lifecycleId, value.metadata.permitId, value.metadata.schemaVersion, value.metadata.version, value.state.recordedAt].every(validText) || !(RUNTIME_PERMIT_LIFECYCLE_STATES as readonly string[]).includes(value.state.value)) return invalid("INVALID_LIFECYCLE", "Lifecycle metadata or state is invalid."); if (value.metadata.permitId !== value.permit.identity.permitId) return invalid("INVALID_REFERENCE", "Lifecycle must reference its permit."); let previous: State = value.permit.status; for (const transition of value.transitions) { if (!validText(transition.occurredAt) || !validText(transition.reference) || !(RUNTIME_PERMIT_LIFECYCLE_STATES as readonly string[]).includes(transition.from) || !(RUNTIME_PERMIT_LIFECYCLE_STATES as readonly string[]).includes(transition.to)) return invalid("INVALID_TRANSITION", "Transition metadata is invalid."); if (transition.from !== previous) return invalid(previous === "expired" || previous === "revoked" ? "TERMINAL_STATE" : "INVALID_TRANSITION", "Transition sequence is invalid."); if (!legal(transition.from, transition.to)) return invalid(transition.from === "expired" || transition.from === "revoked" ? "TERMINAL_STATE" : "INVALID_TRANSITION", "Transition is not allowed."); previous = transition.to; } if (value.state.value !== previous) return invalid("INVALID_TRANSITION", "Lifecycle state must equal its terminal transition."); return deepFreeze({ status: "valid" as const, executable: false as const, authoritative: false as const }); }
export function validateRuntimeExecutionPermitLifecycleResult(lifecycle: RuntimeExecutionPermitLifecycle): Readonly<{ lifecycle: RuntimeExecutionPermitLifecycle; validation: RuntimePermitLifecycleValidation; executable: false; authoritative: false }> { return deepFreeze({ lifecycle, validation: validateRuntimeExecutionPermitLifecycle(lifecycle), executable: false as const, authoritative: false as const }); }
