import { containsNoBehaviour, deepFreeze, validText } from "./validation";

export const RUNTIME_FAILURE_CLASSIFICATIONS = ["transient", "permanent", "partial", "indeterminate", "policy_blocked", "authority_denied", "cancelled", "non_recoverable"] as const;
export const RUNTIME_RECOVERY_ELIGIBILITY = ["eligible", "ineligible", "manual_review_required", "authority_required", "indeterminate"] as const;
export const RUNTIME_RECOVERY_STRATEGIES = ["none", "retry", "resume", "restart", "compensate", "manual_recovery"] as const;
export const RUNTIME_COMPENSATION_STRATEGIES = ["none", "compensating_action", "transactional_reversal", "state_reconciliation", "manual_compensation"] as const;
export const RUNTIME_RECOVERY_READINESS = ["not_required", "blocked", "invalid", "authority_required", "manual_intervention_required"] as const;
export const RUNTIME_TERMINALITY = ["non_terminal", "terminal", "terminal_pending_manual_review", "indeterminate"] as const;
export const RUNTIME_RECOVERY_ERROR_CODES = ["INVALID_RECOVERY_PLAN", "INVALID_FAILURE_CLASSIFICATION", "INVALID_RECOVERY_STRATEGY", "INVALID_COMPENSATION_STRATEGY", "INVALID_MANUAL_INTERVENTION", "INVALID_TERMINALITY", "EXECUTABLE_VALUE_REJECTED"] as const;
type Outcome = "accepted" | "rejected" | "completed" | "failed" | "cancelled" | "blocked";
type Rollback = "none" | "compensating_action" | "transactional" | "manual_recovery";
export interface RuntimeRecoveryPlan { readonly executionId: string; readonly logicalId: string; readonly targetId: string; readonly outcome: Outcome; readonly failure: (typeof RUNTIME_FAILURE_CLASSIFICATIONS)[number]; readonly eligibility: (typeof RUNTIME_RECOVERY_ELIGIBILITY)[number]; readonly strategy: (typeof RUNTIME_RECOVERY_STRATEGIES)[number]; readonly compensation: (typeof RUNTIME_COMPENSATION_STRATEGIES)[number]; readonly rollback: Rollback; readonly manualIntervention: { readonly required: boolean; readonly reasonCode: string; readonly operatorRole: string; readonly escalationClass: string; readonly instructions: readonly string[]; readonly acknowledgmentRequired: boolean }; readonly terminality: (typeof RUNTIME_TERMINALITY)[number]; readonly executable: false; readonly authoritative: false; }
export type RuntimeRecoveryValidation = { readonly status: (typeof RUNTIME_RECOVERY_READINESS)[number]; readonly executable: false; readonly authoritative: false; readonly error?: { readonly code: (typeof RUNTIME_RECOVERY_ERROR_CODES)[number]; readonly message: string } };
function serializable(value: unknown): boolean { if (typeof value === "symbol" || typeof value === "function" || typeof value === "bigint") return false; if (value && typeof value === "object") { if (value instanceof Promise || Object.getPrototypeOf(value) !== Object.prototype && !Array.isArray(value)) return false; return Object.values(value).every(serializable); } return true; }
function invalid(code: (typeof RUNTIME_RECOVERY_ERROR_CODES)[number], message: string): RuntimeRecoveryValidation { return deepFreeze({ status: "invalid" as const, executable: false as const, authoritative: false as const, error: { code, message } }); }
export function createRuntimeRecoveryPlan(input: RuntimeRecoveryPlan): RuntimeRecoveryPlan { if (!containsNoBehaviour(input) || !serializable(input) || input.executable !== false || input.authoritative !== false) throw new TypeError("Invalid Runtime recovery plan."); return deepFreeze({ ...input, manualIntervention: { ...input.manualIntervention, instructions: [...input.manualIntervention.instructions] }, executable: false as const, authoritative: false as const }); }
export function validateRuntimeRecoveryPlan(plan: RuntimeRecoveryPlan): RuntimeRecoveryValidation { if (!Object.isFrozen(plan) || !Object.isFrozen(plan.manualIntervention) || !Object.isFrozen(plan.manualIntervention.instructions) || !containsNoBehaviour(plan) || !serializable(plan) || plan.executable !== false || plan.authoritative !== false) return invalid("EXECUTABLE_VALUE_REJECTED", "Recovery plan must be immutable inert metadata."); if (![plan.executionId, plan.logicalId, plan.targetId].every(validText) || !(RUNTIME_FAILURE_CLASSIFICATIONS as readonly string[]).includes(plan.failure)) return invalid("INVALID_FAILURE_CLASSIFICATION", "Failure metadata is invalid."); if (!(RUNTIME_RECOVERY_STRATEGIES as readonly string[]).includes(plan.strategy) || !(RUNTIME_COMPENSATION_STRATEGIES as readonly string[]).includes(plan.compensation)) return invalid("INVALID_RECOVERY_STRATEGY", "Recovery strategy is invalid."); if (!(RUNTIME_TERMINALITY as readonly string[]).includes(plan.terminality)) return invalid("INVALID_TERMINALITY", "Terminality is invalid."); if (plan.outcome === "completed") return deepFreeze({ status: "not_required" as const, executable: false as const, authoritative: false as const }); if (["blocked", "cancelled"].includes(plan.outcome) || ["authority_denied", "policy_blocked", "non_recoverable"].includes(plan.failure)) { if (plan.strategy !== "none") return invalid("INVALID_RECOVERY_STRATEGY", "Blocked or non-recoverable plans cannot retry."); return deepFreeze({ status: "blocked" as const, executable: false as const, authoritative: false as const }); } if (plan.strategy === "manual_recovery" && !plan.manualIntervention.required) return invalid("INVALID_MANUAL_INTERVENTION", "Manual recovery requires intervention metadata."); if (plan.compensation === "transactional_reversal" && plan.rollback !== "transactional") return invalid("INVALID_COMPENSATION_STRATEGY", "Transactional reversal requires transactional rollback."); if (plan.compensation === "compensating_action" && plan.rollback !== "compensating_action") return invalid("INVALID_COMPENSATION_STRATEGY", "Compensation requires compatible rollback."); if (plan.terminality === "terminal") return deepFreeze({ status: "blocked" as const, executable: false as const, authoritative: false as const }); return deepFreeze({ status: plan.manualIntervention.required ? "manual_intervention_required" as const : "authority_required" as const, executable: false as const, authoritative: false as const }); }
