import type { Workflow } from "@/types";

export const workflows: Workflow[] = [
  {
    id: "wf-lead-qualification",
    name: "Lead Qualification",
    trigger: "New lead created",
    ownerAgent: "Lead Qualifier Agent",
    status: "running",
    successRate: 96,
    runsToday: 23,
    lastRun: "just now",
  },
  {
    id: "wf-proposal-preparation",
    name: "Proposal Preparation",
    trigger: "Lead qualified",
    ownerAgent: "Proposal Agent",
    status: "running",
    successRate: 91,
    runsToday: 7,
    lastRun: "4m ago",
  },
  {
    id: "wf-content-generation",
    name: "Content Generation",
    trigger: "Daily · 09:00",
    ownerAgent: "SEO Agent",
    status: "scheduled",
    successRate: 88,
    runsToday: 1,
    lastRun: "6h ago",
  },
  {
    id: "wf-customer-support",
    name: "Customer Support",
    trigger: "Inbound message",
    ownerAgent: "Support Agent",
    status: "running",
    successRate: 99,
    runsToday: 48,
    lastRun: "just now",
  },
  {
    id: "wf-approval-review",
    name: "Approval Review",
    trigger: "Approval requested",
    ownerAgent: "Sales Agent",
    status: "failed",
    successRate: 74,
    runsToday: 3,
    lastRun: "42m ago",
  },
];

/** Finance Department workflows (v0.5). */
export const financeWorkflows: Workflow[] = [
  {
    id: "wf-invoice-lifecycle",
    name: "Invoice Lifecycle",
    trigger: "Deal won / billing due",
    ownerAgent: "Invoice Agent",
    status: "running",
    successRate: 97,
    runsToday: 27,
    lastRun: "3m ago",
  },
  {
    id: "wf-payment-verification",
    name: "Payment Verification",
    trigger: "Payment received",
    ownerAgent: "Payment Agent",
    status: "running",
    successRate: 95,
    runsToday: 19,
    lastRun: "just now",
  },
  {
    id: "wf-refund-approval",
    name: "Refund Approval",
    trigger: "Refund requested",
    ownerAgent: "Payment Agent",
    status: "idle",
    successRate: 92,
    runsToday: 2,
    lastRun: "yesterday",
  },
  {
    id: "wf-budget-monitoring",
    name: "Budget Monitoring",
    trigger: "Expense recorded · daily",
    ownerAgent: "Budget Agent",
    status: "running",
    successRate: 99,
    runsToday: 12,
    lastRun: "18m ago",
  },
  {
    id: "wf-expense-approval",
    name: "Expense Approval",
    trigger: "Expense detected",
    ownerAgent: "Expense Agent",
    status: "running",
    successRate: 94,
    runsToday: 41,
    lastRun: "1m ago",
  },
  {
    id: "wf-cash-flow-monitoring",
    name: "Cash Flow Monitoring",
    trigger: "Daily · 06:00",
    ownerAgent: "Cash Flow Agent",
    status: "scheduled",
    successRate: 98,
    runsToday: 1,
    lastRun: "6h ago",
  },
  {
    id: "wf-financial-analytics",
    name: "Financial Analytics",
    trigger: "Weekly · Mon 08:00",
    ownerAgent: "Financial Analytics Agent",
    status: "idle",
    successRate: 90,
    runsToday: 0,
    lastRun: "2d ago",
  },
  {
    id: "wf-tax-validation",
    name: "Tax Validation",
    trigger: "Invoice issued",
    ownerAgent: "Tax Agent",
    status: "failed",
    successRate: 81,
    runsToday: 4,
    lastRun: "2h ago",
  },
  {
    id: "wf-compliance-review",
    name: "Compliance Review",
    trigger: "Monthly · country cycle",
    ownerAgent: "Tax Agent",
    status: "scheduled",
    successRate: 88,
    runsToday: 0,
    lastRun: "3d ago",
  },
];
