import type { GovernanceApproval } from "@/features/governance/types";

export const governanceApprovals: GovernanceApproval[] = [
  {
    id: "gov-apr-01",
    title: "Enterprise pricing override for Globex",
    department: "Sales",
    type: "Commercial approval",
    priority: "critical",
    owner: "Director",
    approvalLayer: "executive",
    age: "4h 12m",
    sla: "4h",
    status: "escalated",
    summary: "Discount request exceeds autonomous threshold and changes renewal terms.",
    history: ["Submitted by Negotiation Agent", "Reviewed by Finance Agent", "Escalated to Director"],
  },
  {
    id: "gov-apr-02",
    title: "Policy exception for customer data export",
    department: "Operations",
    type: "Data access exception",
    priority: "high",
    owner: "Legal Agent",
    approvalLayer: "department",
    age: "2h 08m",
    sla: "6h",
    status: "pending",
    summary: "Support workflow needs one-time export for enterprise onboarding remediation.",
    history: ["Submitted by Support Agent", "Compliance checks attached"],
  },
  {
    id: "gov-apr-03",
    title: "Emergency rollback authority for payments flow",
    department: "Finance",
    type: "Emergency approval",
    priority: "critical",
    owner: "Finance Director",
    approvalLayer: "emergency",
    age: "38m",
    sla: "1h",
    status: "pending",
    summary: "Temporary authority requested in case payment retries cross loss threshold.",
    history: ["Created by Payment Agent", "Risk note added by Finance Agent"],
  },
  {
    id: "gov-apr-04",
    title: "High-privilege agent creation",
    department: "HR",
    type: "Role creation",
    priority: "medium",
    owner: "Security Agent",
    approvalLayer: "department",
    age: "5h 21m",
    sla: "8h",
    status: "pending",
    summary: "New Learning Ops agent requests elevated access to onboarding analytics.",
    history: ["Submitted by HR Agent", "Awaiting permission review"],
  },
  {
    id: "gov-apr-05",
    title: "AI policy update publication",
    department: "Director",
    type: "Policy publication",
    priority: "high",
    owner: "Policy Board",
    approvalLayer: "executive",
    age: "1h 17m",
    sla: "12h",
    status: "pending",
    summary: "Revised explainability policy ready for executive sign-off and rollout.",
    history: ["Drafted by Policy Management Agent", "Legal review complete"],
  },
];
