import type { RegistryDefinition } from "@/features/registries/types";

export const registryDefinitions: RegistryDefinition[] = [
  {
    id: "agents",
    title: "Agent Registry",
    shortLabel: "Agents",
    description: "Every agent definition, runtime role and operational owner.",
    route: "/director/registries/agents",
    owner: "Agent Runtime",
    consumers: ["Director", "Workflow Engine", "Governance"],
    dependencies: ["Capabilities", "Tools"],
    totalRecords: 36,
    activeRecords: 28,
    archivedRecords: 8,
    dailyGrowth: 2,
    health: 96,
    synchronization: 98,
    consistency: 97,
    validation: 95,
    coverage: 96,
    freshness: "updated 4m ago",
    status: "healthy",
    recentChanges: 5,
  },
  {
    id: "goals",
    title: "Goal Registry",
    shortLabel: "Goals",
    description: "Strategic goals, success definitions and business ownership.",
    route: "/director/registries/goals",
    owner: "Goal Formation",
    consumers: ["Planning Engine", "Director"],
    dependencies: ["Plans", "Entities"],
    totalRecords: 124,
    activeRecords: 48,
    archivedRecords: 76,
    dailyGrowth: 3,
    health: 94,
    synchronization: 96,
    consistency: 95,
    validation: 93,
    coverage: 94,
    freshness: "updated 9m ago",
    status: "healthy",
    recentChanges: 7,
  },
  {
    id: "plans",
    title: "Plan Registry",
    shortLabel: "Plans",
    description: "Decomposed plans, milestones and orchestration-ready structures.",
    route: "/director/registries/plans",
    owner: "Planning Engine",
    consumers: ["Execution Core", "Governance"],
    dependencies: ["Goals", "Workflows"],
    totalRecords: 286,
    activeRecords: 140,
    archivedRecords: 146,
    dailyGrowth: 6,
    health: 93,
    synchronization: 94,
    consistency: 93,
    validation: 92,
    coverage: 95,
    freshness: "updated 6m ago",
    status: "healthy",
    recentChanges: 12,
  },
  {
    id: "executions",
    title: "Execution Registry",
    shortLabel: "Executions",
    description: "Execution runs, states, outcomes and orchestration lineage.",
    route: "/director/registries/executions",
    owner: "Execution Core",
    consumers: ["Director", "Learning", "Governance"],
    dependencies: ["Plans", "Agents", "Tools"],
    totalRecords: 1284,
    activeRecords: 219,
    archivedRecords: 1065,
    dailyGrowth: 42,
    health: 95,
    synchronization: 97,
    consistency: 96,
    validation: 94,
    coverage: 97,
    freshness: "updated just now",
    status: "healthy",
    recentChanges: 29,
  },
  {
    id: "experience",
    title: "Experience Registry",
    shortLabel: "Experience",
    description: "Execution outcomes converted into indexed organizational experience.",
    route: "/director/registries/experience",
    owner: "Experience Store",
    consumers: ["Learning", "Recommendation Engine"],
    dependencies: ["Executions"],
    totalRecords: 946,
    activeRecords: 811,
    archivedRecords: 135,
    dailyGrowth: 18,
    health: 92,
    synchronization: 95,
    consistency: 92,
    validation: 90,
    coverage: 91,
    freshness: "updated 8m ago",
    status: "attention",
    recentChanges: 16,
  },
  {
    id: "learning",
    title: "Learning Registry",
    shortLabel: "Learning",
    description: "Lessons, adopted improvements and experiment outcomes.",
    route: "/director/registries/learning",
    owner: "Learning Engine",
    consumers: ["Director", "Governance", "Capabilities"],
    dependencies: ["Experience", "Governance"],
    totalRecords: 63,
    activeRecords: 41,
    archivedRecords: 22,
    dailyGrowth: 2,
    health: 91,
    synchronization: 93,
    consistency: 91,
    validation: 90,
    coverage: 89,
    freshness: "updated 22m ago",
    status: "attention",
    recentChanges: 4,
  },
  {
    id: "tools",
    title: "Tool Registry",
    shortLabel: "Tools",
    description: "Available tools, permissions, and operational trust boundaries.",
    route: "/director/registries/tools",
    owner: "Tool Layer",
    consumers: ["Agents", "Governance"],
    dependencies: ["Models", "Capabilities"],
    totalRecords: 58,
    activeRecords: 49,
    archivedRecords: 9,
    dailyGrowth: 1,
    health: 97,
    synchronization: 99,
    consistency: 98,
    validation: 96,
    coverage: 97,
    freshness: "updated 3m ago",
    status: "healthy",
    recentChanges: 3,
  },
  {
    id: "models",
    title: "Model Registry",
    shortLabel: "Models",
    description: "Approved models, routing metadata, cost tiers and usage profiles.",
    route: "/director/registries/models",
    owner: "Model Router",
    consumers: ["Agents", "Director"],
    dependencies: ["Tools"],
    totalRecords: 22,
    activeRecords: 14,
    archivedRecords: 8,
    dailyGrowth: 1,
    health: 96,
    synchronization: 98,
    consistency: 95,
    validation: 95,
    coverage: 94,
    freshness: "updated 13m ago",
    status: "healthy",
    recentChanges: 2,
  },
  {
    id: "capabilities",
    title: "Capability Registry",
    shortLabel: "Capabilities",
    description: "What the platform can do, who consumes it, and where it is safe.",
    route: "/director/registries/capabilities",
    owner: "Capability Planner",
    consumers: ["Agent Runtime", "Director", "Planning Engine"],
    dependencies: ["Models", "Tools", "Learning"],
    totalRecords: 84,
    activeRecords: 70,
    archivedRecords: 14,
    dailyGrowth: 2,
    health: 94,
    synchronization: 95,
    consistency: 94,
    validation: 93,
    coverage: 95,
    freshness: "updated 17m ago",
    status: "healthy",
    recentChanges: 5,
  },
  {
    id: "events",
    title: "Event Registry",
    shortLabel: "Events",
    description: "Platform events, signals, audit triggers and business telemetry.",
    route: "/director/registries/events",
    owner: "Event Bus",
    consumers: ["Director", "Execution", "Governance"],
    dependencies: ["Entities", "Executions"],
    totalRecords: 18420,
    activeRecords: 16208,
    archivedRecords: 2212,
    dailyGrowth: 360,
    health: 93,
    synchronization: 96,
    consistency: 92,
    validation: 91,
    coverage: 94,
    freshness: "updated just now",
    status: "attention",
    recentChanges: 44,
  },
  {
    id: "workflows",
    title: "Workflow Registry",
    shortLabel: "Workflows",
    description: "Workflow definitions, versions and runtime dependencies.",
    route: "/director/registries/workflows",
    owner: "Workflow Engine",
    consumers: ["Execution Core", "Governance", "Finance"],
    dependencies: ["Plans", "Agents", "Tools"],
    totalRecords: 118,
    activeRecords: 64,
    archivedRecords: 54,
    dailyGrowth: 3,
    health: 95,
    synchronization: 97,
    consistency: 94,
    validation: 95,
    coverage: 96,
    freshness: "updated 11m ago",
    status: "healthy",
    recentChanges: 8,
  },
  {
    id: "entities",
    title: "Business Entity Registry",
    shortLabel: "Entities",
    description: "Customers, vendors, departments and business objects used across the system.",
    route: "/director/registries/entities",
    owner: "Entity Service",
    consumers: ["Sales", "Finance", "Legal", "HR"],
    dependencies: ["Events", "Goals"],
    totalRecords: 1486,
    activeRecords: 1310,
    archivedRecords: 176,
    dailyGrowth: 11,
    health: 96,
    synchronization: 97,
    consistency: 96,
    validation: 95,
    coverage: 97,
    freshness: "updated 7m ago",
    status: "healthy",
    recentChanges: 13,
  },
  {
    id: "governance",
    title: "Governance Registry",
    shortLabel: "Governance",
    description: "Approval, policy, compliance and permission records for enterprise control.",
    route: "/director/registries/governance",
    owner: "Governance Core",
    consumers: ["Director", "Legal", "Risk"],
    dependencies: ["Learning", "Executions", "Events"],
    totalRecords: 412,
    activeRecords: 294,
    archivedRecords: 118,
    dailyGrowth: 9,
    health: 97,
    synchronization: 98,
    consistency: 97,
    validation: 96,
    coverage: 98,
    freshness: "updated 5m ago",
    status: "healthy",
    recentChanges: 11,
  },
  {
    id: "risk",
    title: "Risk Registry",
    shortLabel: "Risk",
    description: "Operational, business, AI and compliance risks with ownership and status.",
    route: "/director/registries/risk",
    owner: "Risk Engine",
    consumers: ["Director", "Governance", "Finance", "Legal"],
    dependencies: ["Governance", "Events", "Entities"],
    totalRecords: 205,
    activeRecords: 88,
    archivedRecords: 117,
    dailyGrowth: 2,
    health: 93,
    synchronization: 95,
    consistency: 92,
    validation: 94,
    coverage: 93,
    freshness: "updated 14m ago",
    status: "attention",
    recentChanges: 6,
  },
  {
    id: "policies",
    title: "Policy Registry",
    shortLabel: "Policies",
    description: "Versioned policy records that feed governance, audit and compliance.",
    owner: "Policy Registry",
    consumers: ["Governance", "Legal", "Director"],
    dependencies: ["Governance", "Risk"],
    totalRecords: 73,
    activeRecords: 35,
    archivedRecords: 38,
    dailyGrowth: 1,
    health: 95,
    synchronization: 97,
    consistency: 95,
    validation: 94,
    coverage: 95,
    freshness: "updated 1h ago",
    status: "healthy",
    recentChanges: 3,
  },
];

export const registryDetailOrder = [
  "agents",
  "goals",
  "plans",
  "executions",
  "experience",
  "learning",
  "tools",
  "models",
  "capabilities",
  "events",
  "workflows",
  "entities",
  "governance",
  "risk",
] as const;
