import type { RegistryGrowthPoint, RegistryKey } from "@/features/registries/types";

export const registryGrowthHistory: Record<RegistryKey, RegistryGrowthPoint[]> = {
  agents: [
    { day: "Mon", value: 31 },
    { day: "Tue", value: 32 },
    { day: "Wed", value: 33 },
    { day: "Thu", value: 34 },
    { day: "Fri", value: 35 },
    { day: "Sat", value: 35 },
    { day: "Sun", value: 36 },
  ],
  goals: [
    { day: "Mon", value: 116 },
    { day: "Tue", value: 118 },
    { day: "Wed", value: 119 },
    { day: "Thu", value: 121 },
    { day: "Fri", value: 122 },
    { day: "Sat", value: 123 },
    { day: "Sun", value: 124 },
  ],
  plans: [
    { day: "Mon", value: 260 },
    { day: "Tue", value: 264 },
    { day: "Wed", value: 269 },
    { day: "Thu", value: 273 },
    { day: "Fri", value: 278 },
    { day: "Sat", value: 281 },
    { day: "Sun", value: 286 },
  ],
  executions: [
    { day: "Mon", value: 1028 },
    { day: "Tue", value: 1075 },
    { day: "Wed", value: 1124 },
    { day: "Thu", value: 1179 },
    { day: "Fri", value: 1218 },
    { day: "Sat", value: 1243 },
    { day: "Sun", value: 1284 },
  ],
  experience: [
    { day: "Mon", value: 860 },
    { day: "Tue", value: 878 },
    { day: "Wed", value: 897 },
    { day: "Thu", value: 911 },
    { day: "Fri", value: 924 },
    { day: "Sat", value: 935 },
    { day: "Sun", value: 946 },
  ],
  learning: [
    { day: "Mon", value: 56 },
    { day: "Tue", value: 57 },
    { day: "Wed", value: 58 },
    { day: "Thu", value: 59 },
    { day: "Fri", value: 60 },
    { day: "Sat", value: 61 },
    { day: "Sun", value: 63 },
  ],
  tools: [
    { day: "Mon", value: 55 },
    { day: "Tue", value: 55 },
    { day: "Wed", value: 56 },
    { day: "Thu", value: 56 },
    { day: "Fri", value: 57 },
    { day: "Sat", value: 58 },
    { day: "Sun", value: 58 },
  ],
  models: [
    { day: "Mon", value: 20 },
    { day: "Tue", value: 20 },
    { day: "Wed", value: 21 },
    { day: "Thu", value: 21 },
    { day: "Fri", value: 21 },
    { day: "Sat", value: 22 },
    { day: "Sun", value: 22 },
  ],
  capabilities: [
    { day: "Mon", value: 77 },
    { day: "Tue", value: 78 },
    { day: "Wed", value: 79 },
    { day: "Thu", value: 80 },
    { day: "Fri", value: 81 },
    { day: "Sat", value: 82 },
    { day: "Sun", value: 84 },
  ],
  events: [
    { day: "Mon", value: 16510 },
    { day: "Tue", value: 16900 },
    { day: "Wed", value: 17285 },
    { day: "Thu", value: 17620 },
    { day: "Fri", value: 17995 },
    { day: "Sat", value: 18110 },
    { day: "Sun", value: 18420 },
  ],
  workflows: [
    { day: "Mon", value: 105 },
    { day: "Tue", value: 108 },
    { day: "Wed", value: 111 },
    { day: "Thu", value: 113 },
    { day: "Fri", value: 115 },
    { day: "Sat", value: 116 },
    { day: "Sun", value: 118 },
  ],
  entities: [
    { day: "Mon", value: 1430 },
    { day: "Tue", value: 1440 },
    { day: "Wed", value: 1452 },
    { day: "Thu", value: 1464 },
    { day: "Fri", value: 1470 },
    { day: "Sat", value: 1478 },
    { day: "Sun", value: 1486 },
  ],
  governance: [
    { day: "Mon", value: 380 },
    { day: "Tue", value: 387 },
    { day: "Wed", value: 392 },
    { day: "Thu", value: 398 },
    { day: "Fri", value: 403 },
    { day: "Sat", value: 406 },
    { day: "Sun", value: 412 },
  ],
  risk: [
    { day: "Mon", value: 198 },
    { day: "Tue", value: 199 },
    { day: "Wed", value: 201 },
    { day: "Thu", value: 202 },
    { day: "Fri", value: 203 },
    { day: "Sat", value: 204 },
    { day: "Sun", value: 205 },
  ],
  policies: [
    { day: "Mon", value: 69 },
    { day: "Tue", value: 69 },
    { day: "Wed", value: 70 },
    { day: "Thu", value: 71 },
    { day: "Fri", value: 71 },
    { day: "Sat", value: 72 },
    { day: "Sun", value: 73 },
  ],
};
