import type { RegistryActivity } from "@/features/registries/types";

export const registryTimeline: RegistryActivity[] = [
  {
    id: "rt-1",
    registry: "executions",
    type: "record.added",
    source: "Execution Registry",
    message: "Execution EX-2051 added with latest orchestration lineage and tool trace.",
    severity: "info",
    timestamp: "just now",
  },
  {
    id: "rt-2",
    registry: "governance",
    type: "validation.completed",
    source: "Governance Registry",
    message: "Approval lineage validation completed for all high-priority records.",
    severity: "success",
    timestamp: "11m ago",
  },
  {
    id: "rt-3",
    registry: "experience",
    type: "record.archived",
    source: "Experience Registry",
    message: "Legacy support macro lesson archived after workflow replacement.",
    severity: "warning",
    timestamp: "53m ago",
  },
  {
    id: "rt-4",
    registry: "events",
    type: "schema.updated",
    source: "Event Registry",
    message: "Event payload schema updated to include governance review metadata.",
    severity: "info",
    timestamp: "1h ago",
  },
  {
    id: "rt-5",
    registry: "tools",
    type: "synchronization.completed",
    source: "Tool Registry",
    message: "Connector permission synchronization completed across all active tools.",
    severity: "success",
    timestamp: "2h ago",
  },
  {
    id: "rt-6",
    registry: "risk",
    type: "record.deprecated",
    source: "Risk Registry",
    message: "Legacy vendor exposure record deprecated after remediation closure.",
    severity: "warning",
    timestamp: "5h ago",
  },
  {
    id: "rt-7",
    registry: "agents",
    type: "registry.created",
    source: "Agent Registry",
    message: "Learning Ops agent profile added to active registry inventory.",
    severity: "info",
    timestamp: "6h ago",
  },
];
