CREATE TYPE "public"."actor_type" AS ENUM('human', 'agent', 'system', 'service');--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "companies" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "departments" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "permissions" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "permissions" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "permissions" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "permissions" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "memberships" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "providers" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "agents" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "workflows" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "workflows" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "workflows" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "workflows" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "executions" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "executions" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "executions" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "executions" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "registries" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "registries" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "registries" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "registries" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "integrations" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "integrations" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "integrations" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "integrations" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "commands" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "commands" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "commands" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "commands" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "command_audit" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "command_audit" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "command_audit" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "command_audit" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "telemetry_events" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "telemetry_events" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "telemetry_events" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "telemetry_events" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "approvals" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "policies" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "policies" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "policies" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "policies" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "memories" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "memories" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "memories" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "memories" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "knowledge_edges" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "knowledge_edges" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "knowledge_edges" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "knowledge_edges" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "knowledge_nodes" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "knowledge_nodes" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "knowledge_nodes" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "knowledge_nodes" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "reasoning_traces" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "reasoning_traces" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "reasoning_traces" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "reasoning_traces" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "conversations" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "documents" ADD COLUMN "deleted_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "created_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "updated_by_type" "actor_type";--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "deleted_by" uuid;--> statement-breakpoint
ALTER TABLE "notifications" ADD COLUMN "deleted_by_type" "actor_type";